In [1]:
# import needed libraries

import pandas as pd
import openpyxl

In [2]:
import datetime

In [3]:
# assign sheets to a dataframe
# skip first 12 rows

dict_df = pd.read_excel('Sales Summary on server(SFSgroupAll.REC)3.28.xlsm',
                       sheet_name=['MR1.Guys(REG)', 'MR2.Guys(180Reg)', 'MR3.Guys(REG)12.150', 'MR4.Guys(REG)SKUS', 'MR5.Guys(REG)12.180', 'WR1a.Gals(Reg)', 'WR1b.Gals(Reg)', 'WR.1c.GalsSKU', 'WR.2Gals(Reg) (>120)', 'WR3.Gals(Reg)91.100&150', 'WR4.Gals(Reg)91 (200,205,285)', 'WR5.Gals(REG)800.810.815', 'WR6.Gals(Reg)91(980)', 'WR7.Gals(Reg)93(100)', 'WR8.Gals61-63(2021)', 'WR9.Gals62.185', 'WR10.Gals62.130>14.00', 'WR11a.Gals61&62>$18.5', 'WR11b.Gals63&76>$18.5', 'WR12.Gals91.820(Reg)', 'WR13.Gals93.600&650(Reg)', 'WR14.Gals96', 'WR.15GalsSKU', 'WR16.Gals(REG)SKUS'], skiprows=12)

# , 'WR1.Gals(Reg)', 'WR.1.1GalsSKU', 'WR.2Gals(Reg) (>120)', 'WR3.Gals(Reg)91.100&150', 'WR4.Gals(Reg)91 (200,205,285)', 'WR5.Gals(REG)800.810.815', 'WR6.Gals(Reg)91(980)', 'WR7.Gals(Reg)93(100)', 'WR8.Gals61-63(2021)', 'WR9.Gals62.185', 'WR10.Gals62.130>14.00', 'WR11.Gals61-76>$18.5', 'WR12.Gals91.820(Reg)', 'WR13.Gals93.600&650(Reg)', 'WR14.Gals96', 'WR.15GalsSKU'],

## MR1:
### All DC
### Margin > 19.99
### OH & OO > 0
### Exclude 1/200 SKUs 149132, 149133, 149134

In [4]:
# Margin is filtered within excel
# OH & OO is filtered within excel
# skus are excluded within excel
# python will filter out skus with no receive date and create a dataframe of good skus

In [5]:
# assign first rule to a dataframe

MR1 = dict_df.get("MR1.Guys(REG)")
print(MR1)

            MARGIN       SKU Receive Date Last  \
0           $19.99       NaN               NaN
1           $20.00  960964.0        2023-02-08
2           $20.00  451985.0        2023-03-08
3           $20.00  451986.0        2023-03-08
4           $20.00  451558.0        2023-02-13
...            ...       ...               ...
15731       $99.70  970816.0               NaN
15732       $99.70  968262.0               NaN
15733       $99.75  969149.0        2022-11-14
15734       $99.95  954478.0        2021-07-19
15735  Grand Total       NaN               NaN

                               Class Desc     BRDNM  \
0                                     NaN       NaN
1                      41-800 - Hats/caps    Oakley
2                        12-140 - Ss Tees  JUNKFOOD
3                        12-140 - Ss Tees  JUNKFOOD
4                        12-140 - Ss Tees  JUNKFOOD
...                                   ...       ...
15731                       43-900 - Boot     ARIAT
15732                       43-900 - Boot     ARIAT
15733  41-660 - Guys Watch Metal bracelet    Fossil
15734    41-670 - Guys Watch Leather band     Nixon
15735                                 NaN       NaN

                                      Product Name Retail Price Sale Price  \
0                                              NaN          NaN        NaN
1                      Oakley Original Trucker Hat       $30.00     $30.00
2                     Junkfood Ford Bronco T-Shirt       $29.50     $29.50
3      Junkfood Busch Light&#174; Mountain T-Shirt       $29.50     $29.50
4      Junkfood Coors&#174; Banquet Golden T-Shirt       $29.50     $29.50
...                                            ...          ...        ...
15731                                          NaN      $189.95    $189.95
15732                                          NaN      $189.95    $189.95
15733                         Fossil Everett Watch      $190.00    $190.00
15734               Nixon The Sentry Leather Watch      $175.00    $175.00
15735                                          NaN          NaN        NaN

         Cost  Discount Desc  OH + OO  On Hand Current  \
0         NaN            NaN     3315              771
1      $10.00            NaN     2261             1061
2       $9.50            NaN     1061             1061
3       $9.50            NaN     1034             1034
4       $9.50            NaN      996              996
...       ...            ...      ...              ...
15731  $90.25            NaN      130                0
15732  $90.25            NaN      400                0
15733  $90.25            NaN       14               14
15734  $75.05            NaN        4                4
15735     NaN            NaN  7620978          3240185

       Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  \
0                      19.990000                              2544.0
1                      20.000000                              1200.0
2                      20.000000                                 NaN
3                      20.000000                                 NaN
4                      20.000000                                 NaN
...                          ...                                 ...
15731                  99.700000                               130.0
15732                  99.700000                               400.0
15733                  99.750000                                 NaN
15734                  99.950000                                 NaN
15735                  45.613785                           4380793.0

       SKU6 Count  SKU10 Count
0             1.0            7
1             1.0            1
2             1.0            5
3             1.0            5
4             1.0            5
...           ...          ...
15731         NaN            8
15732         NaN            9
15733         1.0            1
15734         1.0            1
15735     12046.0        96149

[15736 rows x 16 columns]

In [6]:
# see if the column names are correct we have 16 columns

list(MR1.columns)

['MARGIN',
 'SKU',
 'Receive Date Last',
 'Class Desc',
 'BRDNM',
 'Product Name',
 'Retail Price',
 'Sale Price',
 'Cost',
 'Discount Desc',
 'OH + OO',
 'On Hand Current',
 'Average of Margin $ (LCM)',
 'On Order (PO) All Stores and Dates',
 'SKU6 Count',
 'SKU10 Count']

In [7]:
# checking data types

MR1.dtypes

MARGIN                                 object
SKU                                   float64
Receive Date Last                      object
Class Desc                             object
BRDNM                                  object
Product Name                           object
Retail Price                           object
Sale Price                             object
Cost                                   object
Discount Desc                         float64
OH + OO                                 int64
On Hand Current                         int64
Average of Margin $ (LCM)             float64
On Order (PO) All Stores and Dates    float64
SKU6 Count                            float64
SKU10 Count                             int64
dtype: object

In [8]:
# change datatype of MARGIN (may use Average of Margin)
# see if exclusions are included
#

In [9]:
MR1_drop_receive_date = MR1.dropna(subset=['Receive Date Last'])
MR1_drop_receive_date

,MARGIN,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
1,$20.00,960964.0,2023-02-08,41-800 - Hats/caps,Oakley,Oakley Original Trucker Hat,$30.00,$30.00,$10.00,NaN,2261,1061,20.00,1200.0,1.0,1
2,$20.00,451985.0,2023-03-08,12-140 - Ss Tees,JUNKFOOD,Junkfood Ford Bronco T-Shirt,$29.50,$29.50,$9.50,NaN,1061,1061,20.00,NaN,1.0,5
3,$20.00,451986.0,2023-03-08,12-140 - Ss Tees,JUNKFOOD,Junkfood Busch Light&#174; Mountain T-Shirt,$29.50,$29.50,$9.50,NaN,1034,1034,20.00,NaN,1.0,5
4,$20.00,451558.0,2023-02-13,12-140 - Ss Tees,JUNKFOOD,Junkfood Coors&#174; Banquet Golden T-Shirt,$29.50,$29.50,$9.50,NaN,996,996,20.00,NaN,1.0,5
5,$20.00,451983.0,2023-02-15,12-140 - Ss Tees,JUNKFOOD,Junkfood Budweiser&#174; Label T-Shirt,$29.50,$29.50,$9.50,NaN,907,907,20.00,NaN,1.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15728,$99.47,954547.0,2023-03-08,41-250 - Branded Sunglasses,Oakley,Oakley Flak 2.0 XL Prizm&#8482; Sunglasses,$184.00,$184.00,$84.53,NaN,1245,585,99.47,660.0,1.0,1
15729,$99.70,968259.0,2023-03-15,43-900 - Boot,ARIAT,Ariat Sport My Country Leather Cowboy Boot,$189.95,$189.95,$90.25,NaN,170,170,99.70,NaN,1.0,9
15730,$99.70,958296.0,2023-03-07,43-900 - Boot,ARIAT,Ariat Sport VentTEK&#8482; Leather Cowboy Boot,$189.95,$189.95,$90.25,NaN,344,56,99.70,288.0,1.0,8
15733,$99.75,969149.0,2022-11-14,41-660 - Guys Watch Metal bracelet,Fossil,Fossil Everett Watch,$190.00,$190.00,$90.25,NaN,14,14,99.75,NaN,1.0,1
15734,$99.95,954478.0,2021-07-19,41-670 - Guys Watch Leather band,Nixon,Nixon The Sentry Leather Watch,$175.00,$175.00,$75.05,NaN,4,4,99.95,NaN,1.0,1

## MR2
### All DC
### All SKU with Margin > 15.99
### OH & OO > 0
### last receipt > 180 days ago

In [10]:
pd.Timestamp.now()

Timestamp('2023-03-24 08:44:31.627572')

In [11]:
MR2 = dict_df.get("MR2.Guys(180Reg)")
print(MR2)

           MARGIN       SKU Receive Date Last  \
0          $16.00  445391.0        2022-04-27
1          $16.00  968093.0        2022-09-09
2          $16.00  968094.0        2022-09-22
3          $16.00  968095.0        2022-09-09
4          $16.00  445169.0        2022-02-17
...           ...       ...               ...
8593       $98.95  966288.0        2022-08-15
8594       $99.00  966053.0        2022-08-15
8595       $99.00  964701.0        2022-03-04
8596       $99.95  954478.0        2021-07-19
8597  Grand Total       NaN               NaN

                              Class Desc         BRDNM  \
0                       12-140 - Ss Tees  RIOT SOCIETY
1                     41-800 - Hats/caps       SENDERO
2                     41-800 - Hats/caps       SENDERO
3                     41-800 - Hats/caps       SENDERO
4             46-400 - S.s. Woven Shirts    DEPARTWEST
...                                  ...           ...
8593                       43-900 - Boot          Roan
8594  41-660 - Guys Watch Metal bracelet         Guess
8595  41-660 - Guys Watch Metal bracelet         Guess
8596    41-670 - Guys Watch Leather band         Nixon
8597                                 NaN           NaN

                                   Product Name Retail Price Sale Price  \
0             Riot Society Booze Cruise T-Shirt       $25.00     $25.00
1             Sendero Provisions Co. Amigos Hat       $32.00     $32.00
2     Sendero Provisions Co. Cowboy Trucker Hat       $32.00     $32.00
3      Sendero Provisions Co. Shootin' Hand Hat       $32.00     $32.00
4         Boys - Departwest Neon Triangle Shirt       $24.95     $24.95
...                                         ...          ...        ...
8593     Roan by Bed Stu Native II Leather Boot      $164.95    $164.95
8594                        Guess Phoenix Watch      $180.00    $180.00
8595       Guess Gold-Tone Multi-Function Watch      $180.00    $180.00
8596             Nixon The Sentry Leather Watch      $175.00    $175.00
8597                                        NaN          NaN        NaN

        Cost  Discount Desc  OH + OO  On Hand Current  \
0      $9.00            NaN      226              226
1     $16.00            NaN       58               58
2     $16.00            NaN       43               43
3     $16.00            NaN       14               14
4      $8.95            NaN        8                8
...      ...            ...      ...              ...
8593  $66.00            NaN        4                4
8594  $81.00            NaN       32               32
8595  $81.00            NaN       22               22
8596  $75.05            NaN        4                4
8597     NaN            NaN   928096           817020

      Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  \
0                     16.000000                                 NaN
1                     16.000000                                 NaN
2                     16.000000                                 NaN
3                     16.000000                                 NaN
4                     16.000000                                 NaN
...                         ...                                 ...
8593                  98.950000                                 NaN
8594                  99.000000                                 NaN
8595                  99.000000                                 NaN
8596                  99.950000                                 NaN
8597                  40.282843                            111076.0

      SKU6 Count  SKU10 Count
0            1.0            5
1            1.0            1
2            1.0            1
3            1.0            1
4            1.0            5
...          ...          ...
8593         1.0            4
8594         1.0            1
8595         1.0            1
8596         1.0            1
8597      8574.0        47093

[8598 rows x 16 columns]

In [12]:
# change receive date to date time data type 

MR2['Receive Date Last'] = pd.to_datetime(MR2['Receive Date Last'], format='%Y-%m-%d')

In [13]:
MR2.dtypes # checking datatypes

MARGIN                                        object
SKU                                          float64
Receive Date Last                     datetime64[ns]
Class Desc                                    object
BRDNM                                         object
Product Name                                  object
Retail Price                                  object
Sale Price                                    object
Cost                                          object
Discount Desc                                float64
OH + OO                                        int64
On Hand Current                                int64
Average of Margin $ (LCM)                    float64
On Order (PO) All Stores and Dates           float64
SKU6 Count                                   float64
SKU10 Count                                    int64
dtype: object

In [14]:
MR2.head()

,MARGIN,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$16.00,445391.0,2022-04-27,12-140 - Ss Tees,RIOT SOCIETY,Riot Society Booze Cruise T-Shirt,$25.00,$25.00,$9.00,NaN,226,226,16.0,NaN,1.0,5
1,$16.00,968093.0,2022-09-09,41-800 - Hats/caps,SENDERO,Sendero Provisions Co. Amigos Hat,$32.00,$32.00,$16.00,NaN,58,58,16.0,NaN,1.0,1
2,$16.00,968094.0,2022-09-22,41-800 - Hats/caps,SENDERO,Sendero Provisions Co. Cowboy Trucker Hat,$32.00,$32.00,$16.00,NaN,43,43,16.0,NaN,1.0,1
3,$16.00,968095.0,2022-09-09,41-800 - Hats/caps,SENDERO,Sendero Provisions Co. Shootin' Hand Hat,$32.00,$32.00,$16.00,NaN,14,14,16.0,NaN,1.0,1
4,$16.00,445169.0,2022-02-17,46-400 - S.s. Woven Shirts,DEPARTWEST,Boys - Departwest Neon Triangle Shirt,$24.95,$24.95,$8.95,NaN,8,8,16.0,NaN,1.0,5

In [15]:
MR2.info

<bound method DataFrame.info of            MARGIN       SKU Receive Date Last  \
0          $16.00  445391.0        2022-04-27
1          $16.00  968093.0        2022-09-09
2          $16.00  968094.0        2022-09-22
3          $16.00  968095.0        2022-09-09
4          $16.00  445169.0        2022-02-17
...           ...       ...               ...
8593       $98.95  966288.0        2022-08-15
8594       $99.00  966053.0        2022-08-15
8595       $99.00  964701.0        2022-03-04
8596       $99.95  954478.0        2021-07-19
8597  Grand Total       NaN               NaT

                              Class Desc         BRDNM  \
0                       12-140 - Ss Tees  RIOT SOCIETY
1                     41-800 - Hats/caps       SENDERO
2                     41-800 - Hats/caps       SENDERO
3                     41-800 - Hats/caps       SENDERO
4             46-400 - S.s. Woven Shirts    DEPARTWEST
...                                  ...           ...
8593                       43-900 - Boot          Roan
8594  41-660 - Guys Watch Metal bracelet         Guess
8595  41-660 - Guys Watch Metal bracelet         Guess
8596    41-670 - Guys Watch Leather band         Nixon
8597                                 NaN           NaN

                                   Product Name Retail Price Sale Price  \
0             Riot Society Booze Cruise T-Shirt       $25.00     $25.00
1             Sendero Provisions Co. Amigos Hat       $32.00     $32.00
2     Sendero Provisions Co. Cowboy Trucker Hat       $32.00     $32.00
3      Sendero Provisions Co. Shootin' Hand Hat       $32.00     $32.00
4         Boys - Departwest Neon Triangle Shirt       $24.95     $24.95
...                                         ...          ...        ...
8593     Roan by Bed Stu Native II Leather Boot      $164.95    $164.95
8594                        Guess Phoenix Watch      $180.00    $180.00
8595       Guess Gold-Tone Multi-Function Watch      $180.00    $180.00
8596             Nixon The Sentry Leather Watch      $175.00    $175.00
8597                                        NaN          NaN        NaN

        Cost  Discount Desc  OH + OO  On Hand Current  \
0      $9.00            NaN      226              226
1     $16.00            NaN       58               58
2     $16.00            NaN       43               43
3     $16.00            NaN       14               14
4      $8.95            NaN        8                8
...      ...            ...      ...              ...
8593  $66.00            NaN        4                4
8594  $81.00            NaN       32               32
8595  $81.00            NaN       22               22
8596  $75.05            NaN        4                4
8597     NaN            NaN   928096           817020

      Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  \
0                     16.000000                                 NaN
1                     16.000000                                 NaN
2                     16.000000                                 NaN
3                     16.000000                                 NaN
4                     16.000000                                 NaN
...                         ...                                 ...
8593                  98.950000                                 NaN
8594                  99.000000                                 NaN
8595                  99.000000                                 NaN
8596                  99.950000                                 NaN
8597                  40.282843                            111076.0

      SKU6 Count  SKU10 Count
0            1.0            5
1            1.0            1
2            1.0            1
3            1.0            1
4            1.0            5
...          ...          ...
8593         1.0            4
8594         1.0            1
8595         1.0            1
8596         1.0            1
8597      8574.0        47093

[8598 rows x 16 columns]>

In [16]:
MR2_drop_receive_date = MR2.dropna(subset=['Receive Date Last'])
MR2_drop_receive_date

,MARGIN,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$16.00,445391.0,2022-04-27,12-140 - Ss Tees,RIOT SOCIETY,Riot Society Booze Cruise T-Shirt,$25.00,$25.00,$9.00,NaN,226,226,16.00,NaN,1.0,5
1,$16.00,968093.0,2022-09-09,41-800 - Hats/caps,SENDERO,Sendero Provisions Co. Amigos Hat,$32.00,$32.00,$16.00,NaN,58,58,16.00,NaN,1.0,1
2,$16.00,968094.0,2022-09-22,41-800 - Hats/caps,SENDERO,Sendero Provisions Co. Cowboy Trucker Hat,$32.00,$32.00,$16.00,NaN,43,43,16.00,NaN,1.0,1
3,$16.00,968095.0,2022-09-09,41-800 - Hats/caps,SENDERO,Sendero Provisions Co. Shootin' Hand Hat,$32.00,$32.00,$16.00,NaN,14,14,16.00,NaN,1.0,1
4,$16.00,445169.0,2022-02-17,46-400 - S.s. Woven Shirts,DEPARTWEST,Boys - Departwest Neon Triangle Shirt,$24.95,$24.95,$8.95,NaN,8,8,16.00,NaN,1.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8592,$98.66,957980.0,2022-09-09,41-250 - Branded Sunglasses,Oakley,Oakley Ejector Prizm&#8482; Sunglasses,$184.00,$184.00,$85.34,NaN,182,182,98.66,NaN,1.0,1
8593,$98.95,966288.0,2022-08-15,43-900 - Boot,Roan,Roan by Bed Stu Native II Leather Boot,$164.95,$164.95,$66.00,NaN,4,4,98.95,NaN,1.0,4
8594,$99.00,966053.0,2022-08-15,41-660 - Guys Watch Metal bracelet,Guess,Guess Phoenix Watch,$180.00,$180.00,$81.00,NaN,32,32,99.00,NaN,1.0,1
8595,$99.00,964701.0,2022-03-04,41-660 - Guys Watch Metal bracelet,Guess,Guess Gold-Tone Multi-Function Watch,$180.00,$180.00,$81.00,NaN,22,22,99.00,NaN,1.0,1
8596,$99.95,954478.0,2021-07-19,41-670 - Guys Watch Leather band,Nixon,Nixon The Sentry Leather Watch,$175.00,$175.00,$75.05,NaN,4,4,99.95,NaN,1.0,1

In [17]:
MR2_drop_receive_date.sort_values(by='Receive Date Last', ascending=False, inplace = True)
MR2_drop_receive_date

C:\Users\3472340\AppData\Local\Temp\ipykernel_8748\1318449527.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  MR2_drop_receive_date.sort_values(by='Receive Date Last', ascending=False, inplace = True)

,MARGIN,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
5972,$48.95,965787.0,2022-09-25,43-900 - Boot,BKE,BKE Roman Boot,$74.95,$74.95,$26.00,NaN,245,245,48.95,NaN,1.0,7
7538,$60.30,154581.0,2022-09-25,01-200 - Fashion Jeans,BKE,BKE Aiden Boot Stretch Jean,$79.95,$79.95,$19.65,NaN,834,834,60.30,NaN,1.0,11
1450,$20.34,450138.0,2022-09-25,12-140 - Ss Tees,BREW CITY,Brew City Busch Light&#174; Rodeo T-Shirt,$28.95,$28.95,$8.61,NaN,193,193,20.34,NaN,1.0,5
7537,$60.30,154582.0,2022-09-25,01-200 - Fashion Jeans,BKE,BKE Aiden Boot Stretch Jean,$79.95,$79.95,$19.65,NaN,1590,1590,60.30,NaN,1.0,12
8506,$92.66,968603.0,2022-09-25,41-250 - Branded Sunglasses,Oakley,Oakley Hydra Prizm&#8482; Sunglasses,$173.00,$173.00,$80.34,NaN,4,4,92.66,NaN,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3892,$32.97,952352.0,2019-08-30,41-420 - Boxer Shorts,Saxx Underwear,SAXX Daytripper 2 Pack Stretch Boxer Briefs,$48.95,$48.95,$15.98,NaN,2419,19,32.97,2400.0,1.0,5
2987,$26.91,945922.0,2019-08-13,41-450 - Cologne,Veece,Veece Cologne,$34.95,$34.95,$8.04,NaN,33,33,26.91,NaN,1.0,1
1188,$19.45,432391.0,2019-03-18,12-140 - Ss Tees,BREW CITY,Brew City Michelob Ultra&#174; T-Shirt,$28.95,$28.95,$9.50,NaN,300,0,19.45,300.0,NaN,5
1354,$19.88,940695.0,2016-11-23,41-800 - Hats/caps,Fox Head,Fox Signature Stretch Hat,$29.95,$29.95,$10.07,NaN,1800,0,19.88,1800.0,NaN,2
8247,$71.54,929017.0,2016-10-28,43-900 - Boot,Dr Martens,Dr. Martens Combs Boot,$110.00,$110.00,$38.46,NaN,200,0,71.54,200.0,NaN,7

## MR3
### 12/150
### All SKU
### Margin >15.99
### OH & OO > 0

In [18]:
# Assign rule to dataframe
MR3 = dict_df.get("MR3.Guys(REG)12.150")
print(MR3)

         MARGIN       SKU Receive Date Last  \
0        $16.49  441064.0        2021-02-10
1        $17.45  445841.0        2022-02-02
2        $17.70  440617.0        2021-02-04
3        $17.70  443526.0        2021-11-02
4        $17.71  440618.0        2021-02-08
5        $18.55  451159.0        2022-10-28
6        $19.70  445834.0        2022-02-22
7        $19.70  445833.0        2022-02-10
8        $38.50  445557.0        2021-11-08
9        $38.50  445554.0        2021-10-28
10       $38.50  445556.0        2021-11-01
11  Grand Total       NaN               NaN

                            Class Desc        BRDNM  \
0   12-150 - Ss Regional & holiday tee    BREW CITY
1   12-150 - Ss Regional & holiday tee         Buzz
2   12-150 - Ss Regional & holiday tee         Buzz
3   12-150 - Ss Regional & holiday tee         Buzz
4   12-150 - Ss Regional & holiday tee         Buzz
5   12-150 - Ss Regional & holiday tee  Tipsy Elves
6   12-150 - Ss Regional & holiday tee      OLD ROW
7   12-150 - Ss Regional & holiday tee      OLD ROW
8   12-150 - Ss Regional & holiday tee      Pro Max
9   12-150 - Ss Regional & holiday tee      Pro Max
10  12-150 - Ss Regional & holiday tee      Pro Max
11                                 NaN          NaN

                                         Product Name Retail Price Sale Price  \
0                 Brew City Feeling Bud Lucky T-Shirt       $24.95     $24.95
1                      Buzz Boozed & Confused T-Shirt       $24.95     $24.95
2                              Buzz Lucked Up T-Shirt       $24.95     $24.95
3   Buzz Let's Have An Old Fashioned Christmas T-S...       $24.95     $24.95
4                        Buzz Rub Me For Luck T-Shirt       $24.95     $24.95
5                   Tipsy Elves Ain't No Laws T-Shirt       $28.95     $28.95
6                     Old Row St. Paddys Buck T-Shirt       $32.95     $32.95
7                            Old Row Shamrock T-Shirt       $32.95     $32.95
8    Pro Standard Pittsburgh Steelers Warm Up T-Shirt       $70.00     $70.00
9     Pro Standard New Orleans Saints Warm Up T-Shirt       $70.00     $70.00
10     Pro Standard Las Vegas Raiders Warm Up T-Shirt       $70.00     $70.00
11                                                NaN          NaN        NaN

      Cost  Discount Desc  OH + OO  On Hand Current  \
0    $8.46            NaN       38               38
1    $7.50            NaN       44               44
2    $7.25            NaN      123              123
3    $7.25            NaN       46               46
4    $7.24            NaN       58               58
5   $10.40            NaN       87               87
6   $13.25            NaN      157              157
7   $13.25            NaN       53               53
8   $31.50            NaN       14               14
9   $31.50            NaN        4                4
10  $31.50            NaN        1                1
11     NaN            NaN      625              625

    Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  SKU6 Count  \
0                   16.490000                                 NaN           1
1                   17.450000                                 NaN           1
2                   17.700000                                 NaN           1
3                   17.700000                                 NaN           1
4                   17.710000                                 NaN           1
5                   18.550000                                 NaN           1
6                   19.700000                                 NaN           1
7                   19.700000                                 NaN           1
8                   38.500000                                 NaN           1
9                   38.500000                                 NaN           1
10                  38.500000                                 NaN           1
11                  23.681818                                 NaN          11

    SKU10 Count
0             5
1             5
2             5
3             5
4             5
5             5
6             3
7             5
8             4
9             3
10            1
11           46

In [19]:
MR3.head()

,MARGIN,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$16.49,441064.0,2021-02-10,12-150 - Ss Regional & holiday tee,BREW CITY,Brew City Feeling Bud Lucky T-Shirt,$24.95,$24.95,$8.46,NaN,38,38,16.49,NaN,1,5
1,$17.45,445841.0,2022-02-02,12-150 - Ss Regional & holiday tee,Buzz,Buzz Boozed & Confused T-Shirt,$24.95,$24.95,$7.50,NaN,44,44,17.45,NaN,1,5
2,$17.70,440617.0,2021-02-04,12-150 - Ss Regional & holiday tee,Buzz,Buzz Lucked Up T-Shirt,$24.95,$24.95,$7.25,NaN,123,123,17.70,NaN,1,5
3,$17.70,443526.0,2021-11-02,12-150 - Ss Regional & holiday tee,Buzz,Buzz Let's Have An Old Fashioned Christmas T-S...,$24.95,$24.95,$7.25,NaN,46,46,17.70,NaN,1,5
4,$17.71,440618.0,2021-02-08,12-150 - Ss Regional & holiday tee,Buzz,Buzz Rub Me For Luck T-Shirt,$24.95,$24.95,$7.24,NaN,58,58,17.71,NaN,1,5

In [20]:
MR3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 16 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   MARGIN                              12 non-null     object
 1   SKU                                 11 non-null     float64
 2   Receive Date Last                   11 non-null     object
 3   Class Desc                          11 non-null     object
 4   BRDNM                               11 non-null     object
 5   Product Name                        11 non-null     object
 6   Retail Price                        11 non-null     object
 7   Sale Price                          11 non-null     object
 8   Cost                                11 non-null     object
 9   Discount Desc                       0 non-null      float64
 10  OH + OO                             12 non-null     int64
 11  On Hand Current                     12 non-null     int64
 12  Average of Margin $ (LCM)           12 non-null     float64
 13  On Order (PO) All Stores and Dates  0 non-null      float64
 14  SKU6 Count                          12 non-null     int64
 15  SKU10 Count                         12 non-null     int64
dtypes: float64(4), int64(4), object(8)
memory usage: 1.6+ KB

In [21]:
MR3_drop_receive_date = MR3.dropna(subset=['Receive Date Last'])
MR3_drop_receive_date

,MARGIN,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$16.49,441064.0,2021-02-10,12-150 - Ss Regional & holiday tee,BREW CITY,Brew City Feeling Bud Lucky T-Shirt,$24.95,$24.95,$8.46,NaN,38,38,16.49,NaN,1,5
1,$17.45,445841.0,2022-02-02,12-150 - Ss Regional & holiday tee,Buzz,Buzz Boozed & Confused T-Shirt,$24.95,$24.95,$7.50,NaN,44,44,17.45,NaN,1,5
2,$17.70,440617.0,2021-02-04,12-150 - Ss Regional & holiday tee,Buzz,Buzz Lucked Up T-Shirt,$24.95,$24.95,$7.25,NaN,123,123,17.70,NaN,1,5
3,$17.70,443526.0,2021-11-02,12-150 - Ss Regional & holiday tee,Buzz,Buzz Let's Have An Old Fashioned Christmas T-S...,$24.95,$24.95,$7.25,NaN,46,46,17.70,NaN,1,5
4,$17.71,440618.0,2021-02-08,12-150 - Ss Regional & holiday tee,Buzz,Buzz Rub Me For Luck T-Shirt,$24.95,$24.95,$7.24,NaN,58,58,17.71,NaN,1,5
5,$18.55,451159.0,2022-10-28,12-150 - Ss Regional & holiday tee,Tipsy Elves,Tipsy Elves Ain't No Laws T-Shirt,$28.95,$28.95,$10.40,NaN,87,87,18.55,NaN,1,5
6,$19.70,445834.0,2022-02-22,12-150 - Ss Regional & holiday tee,OLD ROW,Old Row St. Paddys Buck T-Shirt,$32.95,$32.95,$13.25,NaN,157,157,19.70,NaN,1,3
7,$19.70,445833.0,2022-02-10,12-150 - Ss Regional & holiday tee,OLD ROW,Old Row Shamrock T-Shirt,$32.95,$32.95,$13.25,NaN,53,53,19.70,NaN,1,5
8,$38.50,445557.0,2021-11-08,12-150 - Ss Regional & holiday tee,Pro Max,Pro Standard Pittsburgh Steelers Warm Up T-Shirt,$70.00,$70.00,$31.50,NaN,14,14,38.50,NaN,1,4
9,$38.50,445554.0,2021-10-28,12-150 - Ss Regional & holiday tee,Pro Max,Pro Standard New Orleans Saints Warm Up T-Shirt,$70.00,$70.00,$31.50,NaN,4,4,38.50,NaN,1,3
10,$38.50,445556.0,2021-11-01,12-150 - Ss Regional & holiday tee,Pro Max,Pro Standard Las Vegas Raiders Warm Up T-Shirt,$70.00,$70.00,$31.50,NaN,1,1,38.50,NaN,1,1

## MR4
### include 310297, 310298, 310607, 310608, 310770, 310771, 310772

In [22]:
# Assign rule to dataframe
MR4 = dict_df.get("MR4.Guys(REG)SKUS")
print(MR4)

        MARGIN       SKU Receive Date Last                   Class Desc  \
0       $16.50  310772.0        2022-03-14  46-320 - Youth Board Shorts
1       $19.20  310297.0        2022-01-26   46-330 - Youth Knit Shorts
2       $19.20  310298.0        2021-12-27   46-330 - Youth Knit Shorts
3       $19.20  310608.0        2022-02-11  46-310 - Youth Twill Shorts
4       $19.25  310771.0        2022-03-14  46-320 - Youth Board Shorts
5       $19.25  310770.0        2022-03-14  46-320 - Youth Board Shorts
6       $21.05  310607.0        2023-02-08  46-310 - Youth Twill Shorts
7  Grand Total       NaN               NaN                          NaN

           BRDNM                                   Product Name Retail Price  \
0     DEPARTWEST  Boys - Departwest Flamingo Stretch Boardshort       $29.50
1            BKE            Boys - BKE Harold Performance Short       $29.95
2            BKE            Boys - BKE Harold Performance Short       $29.95
3  Hurley - Kids  Little Boys - Hurley Hybrid Stretch Walkshort       $32.00
4     DEPARTWEST   Boys - Departwest Tie-Dye Stretch Boardshort       $29.50
5     DEPARTWEST              Boys - Departwest Flag Boardshort       $29.50
6  Hurley - Kids  Little Boys - Hurley Hybrid Stretch Walkshort       $35.00
7            NaN                                            NaN          NaN

  Sale Price    Cost  Discount Desc  OH + OO  On Hand Current  \
0     $29.50  $13.00            NaN        5                5
1     $29.95  $10.75            NaN      127              127
2     $29.95  $10.75            NaN      120              120
3     $32.00  $12.80            NaN        1                1
4     $29.50  $10.25            NaN      136              136
5     $29.50  $10.25            NaN        8                8
6     $35.00  $13.95            NaN      240              240
7        NaN     NaN            NaN      637              637

   Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  SKU6 Count  \
0                  16.500000                                 NaN           1
1                  19.200000                                 NaN           1
2                  19.200000                                 NaN           1
3                  19.200000                                 NaN           1
4                  19.250000                                 NaN           1
5                  19.250000                                 NaN           1
6                  21.050000                                 NaN           1
7                  19.092857                                 NaN           7

   SKU10 Count
0            3
1            5
2            5
3            1
4            4
5            4
6            4
7           26

In [23]:
MR4_drop_receive_date = MR4.dropna(subset=['Receive Date Last'])
MR4_drop_receive_date

,MARGIN,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$16.50,310772.0,2022-03-14,46-320 - Youth Board Shorts,DEPARTWEST,Boys - Departwest Flamingo Stretch Boardshort,$29.50,$29.50,$13.00,NaN,5,5,16.50,NaN,1,3
1,$19.20,310297.0,2022-01-26,46-330 - Youth Knit Shorts,BKE,Boys - BKE Harold Performance Short,$29.95,$29.95,$10.75,NaN,127,127,19.20,NaN,1,5
2,$19.20,310298.0,2021-12-27,46-330 - Youth Knit Shorts,BKE,Boys - BKE Harold Performance Short,$29.95,$29.95,$10.75,NaN,120,120,19.20,NaN,1,5
3,$19.20,310608.0,2022-02-11,46-310 - Youth Twill Shorts,Hurley - Kids,Little Boys - Hurley Hybrid Stretch Walkshort,$32.00,$32.00,$12.80,NaN,1,1,19.20,NaN,1,1
4,$19.25,310771.0,2022-03-14,46-320 - Youth Board Shorts,DEPARTWEST,Boys - Departwest Tie-Dye Stretch Boardshort,$29.50,$29.50,$10.25,NaN,136,136,19.25,NaN,1,4
5,$19.25,310770.0,2022-03-14,46-320 - Youth Board Shorts,DEPARTWEST,Boys - Departwest Flag Boardshort,$29.50,$29.50,$10.25,NaN,8,8,19.25,NaN,1,4
6,$21.05,310607.0,2023-02-08,46-310 - Youth Twill Shorts,Hurley - Kids,Little Boys - Hurley Hybrid Stretch Walkshort,$35.00,$35.00,$13.95,NaN,240,240,21.05,NaN,1,4

## MR5
### 12/180
### ALL SKU
### Review at end of summer

In [24]:
# Assign rule to dataframe
MR5 = dict_df.get("MR5.Guys(REG)12.180")
print(MR5)

          MARGIN       SKU Receive Date Last          Class Desc  \
0         $11.02  440325.0        2021-05-06  12-180 - Tank Tops
1         $11.64  440324.0        2021-05-06  12-180 - Tank Tops
2         $11.70  440718.0        2021-05-17  12-180 - Tank Tops
3         $11.70  441395.0        2021-06-01  12-180 - Tank Tops
4         $11.75  430983.0               NaN  12-180 - Tank Tops
..           ...       ...               ...                 ...
427       $30.00  450758.0               NaN  12-180 - Tank Tops
428       $30.00  449965.0               NaN  12-180 - Tank Tops
429       $30.00  449909.0               NaN  12-180 - Tank Tops
430       $42.24  422954.0               NaN  12-180 - Tank Tops
431  Grand Total       NaN               NaN                 NaN

                  BRDNM                      Product Name Retail Price  \
0                   BKE              BKE Striped Tank Top       $16.95
1                   BKE                BKE Basic Tank Top       $16.95
2                  NOVA  Nova Industries Streaky Tank Top       $16.95
3            DEPARTWEST    Departwest Space Dyed Tank Top       $16.95
4            DEPARTWEST                               NaN       $16.50
..                  ...                               ...          ...
427                Rvca                               NaN       $50.00
428          AFFLICTION                               NaN       $48.00
429                Rvca                               NaN       $50.00
430  Calvin Klein Jeans                               NaN       $69.00
431                 NaN                               NaN          NaN

    Sale Price    Cost  Discount Desc   OH + OO  On Hand Current  \
0       $16.95   $5.93            NaN       7.0              7.0
1       $16.95   $5.31            NaN       7.0              7.0
2       $16.95   $5.25            NaN      36.0             36.0
3       $16.95   $5.25            NaN       NaN              NaN
4       $16.50   $4.75            NaN       NaN              NaN
..         ...     ...            ...       ...              ...
427     $50.00  $20.00            NaN     120.0              0.0
428     $48.00  $18.00            NaN     600.0              0.0
429     $50.00  $20.00            NaN     300.0              0.0
430     $69.00  $26.76            NaN       NaN              NaN
431        NaN     NaN            NaN  100224.0          58833.0

     Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  \
0                    11.020000                                 NaN
1                    11.640000                                 NaN
2                    11.700000                                 NaN
3                    11.700000                                 NaN
4                    11.750000                                 NaN
..                         ...                                 ...
427                  30.000000                               120.0
428                  30.000000                               600.0
429                  30.000000                               300.0
430                  42.240000                                 NaN
431                  17.339536                             41391.0

     SKU6 Count  SKU10 Count
0           1.0          3.0
1           1.0          4.0
2           1.0          5.0
3           NaN          NaN
4           NaN          NaN
..          ...          ...
427         NaN          5.0
428         NaN          6.0
429         NaN          5.0
430         NaN          NaN
431       232.0       1408.0

[432 rows x 16 columns]

In [25]:
MR5_drop_receive_date = MR5.dropna(subset=['Receive Date Last'])
MR5_drop_receive_date

,MARGIN,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$11.02,440325.0,2021-05-06,12-180 - Tank Tops,BKE,BKE Striped Tank Top,$16.95,$16.95,$5.93,NaN,7.0,7.0,11.02,NaN,1.0,3.0
1,$11.64,440324.0,2021-05-06,12-180 - Tank Tops,BKE,BKE Basic Tank Top,$16.95,$16.95,$5.31,NaN,7.0,7.0,11.64,NaN,1.0,4.0
2,$11.70,440718.0,2021-05-17,12-180 - Tank Tops,NOVA,Nova Industries Streaky Tank Top,$16.95,$16.95,$5.25,NaN,36.0,36.0,11.70,NaN,1.0,5.0
3,$11.70,441395.0,2021-06-01,12-180 - Tank Tops,DEPARTWEST,Departwest Space Dyed Tank Top,$16.95,$16.95,$5.25,NaN,NaN,NaN,11.70,NaN,NaN,NaN
5,$11.94,444959.0,2022-02-17,12-180 - Tank Tops,DEPARTWEST,Departwest Marled Tank Top,$16.95,$16.95,$5.01,NaN,110.0,110.0,11.94,NaN,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,$30.00,449964.0,2023-03-14,12-180 - Tank Tops,AFFLICTION,Affliction Feint Illusion Tank Top,$48.00,$48.00,$18.00,NaN,798.0,798.0,30.00,NaN,1.0,6.0
422,$30.00,445294.0,2022-01-28,12-180 - Tank Tops,AFFLICTION,Affliction Code Of Honor Tank Top,$48.00,$48.00,$18.00,NaN,21.0,21.0,30.00,NaN,1.0,5.0
423,$30.00,445291.0,2022-03-02,12-180 - Tank Tops,AFFLICTION,Affliction Rise Of The Fallen Tank Top,$48.00,$48.00,$18.00,NaN,9.0,9.0,30.00,NaN,1.0,6.0
424,$30.00,445293.0,2022-01-13,12-180 - Tank Tops,AFFLICTION,Affliction American Customs Native Petrol Tank...,$48.00,$48.00,$18.00,NaN,7.0,7.0,30.00,NaN,1.0,4.0
425,$30.00,439532.0,2021-03-30,12-180 - Tank Tops,AFFLICTION,Affliction American Customs Iron Grease Tank Top,$48.00,$48.00,$18.00,NaN,7.0,7.0,30.00,NaN,1.0,5.0

## WR1a 
### SKU with Margin > 19.99
### OH & OO > 0
### include 96
### DC 51, 56, 63, 76, 81, 86, 91, 93, 96
### No receipt exclusion

In [26]:
# Assign rule to dataframe
WR1A = dict_df.get("WR1a.Gals(Reg)")
print(WR1A)

           Margin       SKU Receive Date Last                   Class Desc  \
0          $19.99  969213.0        2023-03-15        91-820 - Fashion Hats
1          $19.99  968885.0        2023-02-28               91-100 - Belts
2          $19.99  969275.0        2023-02-22  91-205 - Specialty Earrings
3          $19.99  969214.0        2023-02-28        91-820 - Fashion Hats
4          $19.99  969215.0        2023-03-06        91-820 - Fashion Hats
...           ...       ...               ...                          ...
8971       $99.74  947678.0        2022-11-22    93-850 - Functional Boots
8972       $99.82  949724.0        2018-11-13  91-305 - Branded Sunglasses
8973       $99.83  706053.0               NaN   86-625 - Casual Hvwt Coats
8974       $99.90  967373.0        2022-10-10          93-900 - Tall Boots
8975  Grand Total       NaN               NaN                          NaN

                  BRDNM                                       Product Name  \
0         David & Young                         Whiskey Is Key Trucker Hat
1                   BKE                            BKE Metallic Glitz Belt
2     STERLING & STITCH  Sterling &#38; Stitch Western Fringe Drop Earring
3         David & Young               David & Young Live It Up Trucker Hat
4         David & Young            David & Young Adios Beaches Trucker Hat
...                 ...                                                ...
8971         Dr Martens                    Dr. Martens Pascal Leather Boot
8972             Rayban           Ray-Ban&#174; Clubround Fleck Sunglasses
8973    Z Supply Active                                                NaN
8974        Azalea Wang        Azalea Wang Texas Studded Tall Western Boot
8975                NaN                                                NaN

     Retail Price Sale Price    Cost  Discount Desc  OH + OO  On Hand Current  \
0          $24.99     $24.99   $5.00            NaN     1437             1437
1          $24.99     $24.99   $5.00            NaN     1025             1025
2          $22.99     $22.99   $3.00            NaN      537              537
3          $24.99     $24.99   $5.00            NaN      469              469
4          $24.99     $24.99   $5.00            NaN      452              452
...           ...        ...     ...            ...      ...              ...
8971      $170.00    $170.00  $70.26            NaN      242              242
8972      $180.00    $180.00  $80.18            NaN        9                9
8973      $149.00    $149.00  $49.17            NaN      120                0
8974      $179.90    $179.90  $80.00            NaN      118               10
8975          NaN        NaN     NaN            NaN  4153129          1582460

      Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  \
0                     19.990000                                 NaN
1                     19.990000                                 NaN
2                     19.990000                                 NaN
3                     19.990000                                 NaN
4                     19.990000                                 NaN
...                         ...                                 ...
8971                  99.740000                                 NaN
8972                  99.820000                                 NaN
8973                  99.830000                               120.0
8974                  99.900000                               108.0
8975                  51.269991                           2570669.0

      SKU6 Count  SKU10 Count
0            1.0            1
1            1.0            4
2            1.0            1
3            1.0            1
4            1.0            1
...          ...          ...
8971         1.0            7
8972         1.0            1
8973         NaN            5
8974         1.0            9
8975      6920.0        63200

[8976 rows x 16 columns]

In [27]:
WR1A_drop_receive_date = WR1A.dropna(subset=['Receive Date Last'])
WR1A_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$19.99,969213.0,2023-03-15,91-820 - Fashion Hats,David & Young,Whiskey Is Key Trucker Hat,$24.99,$24.99,$5.00,NaN,1437,1437,19.99,NaN,1.0,1
1,$19.99,968885.0,2023-02-28,91-100 - Belts,BKE,BKE Metallic Glitz Belt,$24.99,$24.99,$5.00,NaN,1025,1025,19.99,NaN,1.0,4
2,$19.99,969275.0,2023-02-22,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Western Fringe Drop Earring,$22.99,$22.99,$3.00,NaN,537,537,19.99,NaN,1.0,1
3,$19.99,969214.0,2023-02-28,91-820 - Fashion Hats,David & Young,David & Young Live It Up Trucker Hat,$24.99,$24.99,$5.00,NaN,469,469,19.99,NaN,1.0,1
4,$19.99,969215.0,2023-03-06,91-820 - Fashion Hats,David & Young,David & Young Adios Beaches Trucker Hat,$24.99,$24.99,$5.00,NaN,452,452,19.99,NaN,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8969,$99.68,958172.0,2021-04-14,91-305 - Branded Sunglasses,Rayban,Ray-Ban&#174; Double Bridge Aviator Sunglasses,$174.00,$174.00,$74.32,NaN,1,1,99.68,NaN,1.0,1
8970,$99.70,963282.0,2022-03-28,93-980 - Western Boots,ARIAT,Ariat Blanket Dixon Western Leather Ankle Boot,$189.95,$189.95,$90.25,NaN,109,109,99.70,NaN,1.0,9
8971,$99.74,947678.0,2022-11-22,93-850 - Functional Boots,Dr Martens,Dr. Martens Pascal Leather Boot,$170.00,$170.00,$70.26,NaN,242,242,99.74,NaN,1.0,7
8972,$99.82,949724.0,2018-11-13,91-305 - Branded Sunglasses,Rayban,Ray-Ban&#174; Clubround Fleck Sunglasses,$180.00,$180.00,$80.18,NaN,9,9,99.82,NaN,1.0,1
8974,$99.90,967373.0,2022-10-10,93-900 - Tall Boots,Azalea Wang,Azalea Wang Texas Studded Tall Western Boot,$179.90,$179.90,$80.00,NaN,118,10,99.90,108.0,1.0,9

## WR1B
### DC 61 & 62
### Receipts > 10 days

In [28]:
# Assign rule to dataframe
WR1B = dict_df.get("WR1b.Gals(Reg)")
print(WR1B)

           Margin       SKU Receive Date Last  \
0          $20.00  542390.0        2022-04-18
1          $20.00  548392.0               NaN
2          $20.07  539913.0        2021-05-17
3          $20.08  539368.0        2021-06-11
4          $20.09  547056.0        2023-01-23
...           ...       ...               ...
3877       $81.69  545608.0        2022-09-28
3878       $90.00  548301.0               NaN
3879       $90.00  548291.0               NaN
3880       $92.00  545987.0        2022-11-16
3881  Grand Total       NaN               NaN

                              Class Desc         BRDNM  \
0        62-130 - S/s Branded Tee shirts          Reef
1                     62-178 - Bralettes   FREE PEOPLE
2                     62-178 - Bralettes  BKEssentials
3                     62-178 - Bralettes  BKEssentials
4           62-182 - Fashion Basic Tanks       DAYTRIP
...                                  ...           ...
3877  61-720 - 3/4 Ls Slv synthc bt frnt   FREE PEOPLE
3878   62-460 - Sleeved Knit Bttn fronts      Z Supply
3879   62-460 - Sleeved Knit Bttn fronts      Z Supply
3880          62-620 - L/s Fashion Knits   FREE PEOPLE
3881                                 NaN           NaN

                                  Product Name Retail Price Sale Price  \
0                   Reef Power Relaxed T-Shirt       $30.00     $30.00
1                                          NaN       $40.00     $40.00
2        BKEssentials Seamless V-Neck Bralette       $29.95     $29.95
3                    BKEssentials Ribbed Brami       $24.95     $24.95
4               Daytrip Lace Layering Tank Top       $29.99     $29.99
...                                        ...          ...        ...
3877         Free People My Best Velvet Blouse      $148.00    $148.00
3878                                       NaN      $129.00    $129.00
3879                                       NaN      $129.00    $129.00
3880  Free People Pixie Crinkle Tunic Pullover      $168.00    $168.00
3881                                       NaN          NaN        NaN

        Cost  Discount Desc  OH + OO  On Hand Current  \
0     $10.00            NaN        6                6
1     $20.00            NaN      350                0
2      $9.88            NaN       47               47
3      $4.87            NaN        1                1
4      $9.90            NaN     1236             1236
...      ...            ...      ...              ...
3877  $66.31            NaN       16               16
3878  $39.00            NaN      480                0
3879  $39.00            NaN      600                0
3880  $76.00            NaN        8                8
3881     NaN            NaN  2324430           755748

      Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  \
0                     20.000000                                 NaN
1                     20.000000                               350.0
2                     20.070000                                 NaN
3                     20.080000                                 NaN
4                     20.090000                                 NaN
...                         ...                                 ...
3877                  81.690000                                 NaN
3878                  90.000000                               480.0
3879                  90.000000                               600.0
3880                  92.000000                                 NaN
3881                  29.000327                           1568682.0

      SKU6 Count  SKU10 Count
0            1.0            5
1            NaN            3
2            1.0            2
3            1.0            1
4            1.0            5
...          ...          ...
3877         1.0            5
3878         NaN            5
3879         NaN            6
3880         1.0            4
3881      2820.0        18466

[3882 rows x 16 columns]

In [29]:
WR1B_drop_receive_date = WR1B.dropna(subset=['Receive Date Last'])
WR1B_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$20.00,542390.0,2022-04-18,62-130 - S/s Branded Tee shirts,Reef,Reef Power Relaxed T-Shirt,$30.00,$30.00,$10.00,NaN,6,6,20.00,NaN,1.0,5
2,$20.07,539913.0,2021-05-17,62-178 - Bralettes,BKEssentials,BKEssentials Seamless V-Neck Bralette,$29.95,$29.95,$9.88,NaN,47,47,20.07,NaN,1.0,2
3,$20.08,539368.0,2021-06-11,62-178 - Bralettes,BKEssentials,BKEssentials Ribbed Brami,$24.95,$24.95,$4.87,NaN,1,1,20.08,NaN,1.0,1
4,$20.09,547056.0,2023-01-23,62-182 - Fashion Basic Tanks,DAYTRIP,Daytrip Lace Layering Tank Top,$29.99,$29.99,$9.90,NaN,1236,1236,20.09,NaN,1.0,5
5,$20.09,547055.0,2023-01-23,62-182 - Fashion Basic Tanks,DAYTRIP,Daytrip Lace Layering Tank Top,$29.99,$29.99,$9.90,NaN,1116,1116,20.09,NaN,1.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3868,$70.40,544964.0,2022-09-21,62-840 - L/s 3/4 Slv sweatshirts,Wanakome,Wanakome Becky Quarter Zip Pullover,$110.00,$110.00,$39.60,NaN,1,1,70.40,NaN,1.0,1
3870,$72.55,543438.0,2022-02-18,62-840 - L/s 3/4 Slv sweatshirts,Wanakome,Wanakome Shelina Lace-Up Hooded Sweatshirt,$114.95,$114.95,$42.40,NaN,9,9,72.55,NaN,1.0,4
3876,$81.00,545607.0,2022-09-27,61-720 - 3/4 Ls Slv synthc bt frnt,FREE PEOPLE,Free People My Best Velvet Blouse,$148.00,$148.00,$67.00,NaN,17,17,81.00,NaN,1.0,5
3877,$81.69,545608.0,2022-09-28,61-720 - 3/4 Ls Slv synthc bt frnt,FREE PEOPLE,Free People My Best Velvet Blouse,$148.00,$148.00,$66.31,NaN,16,16,81.69,NaN,1.0,5
3880,$92.00,545987.0,2022-11-16,62-620 - L/s Fashion Knits,FREE PEOPLE,Free People Pixie Crinkle Tunic Pullover,$168.00,$168.00,$76.00,NaN,8,8,92.00,NaN,1.0,4

## WR1C
### Add 533479, 534813
### Expose  309417, 309419

In [30]:
# Assign rule to dataframe
WR1C = dict_df.get("WR.1c.GalsSKU")
print(WR1C)

        Margin       SKU Receive Date Last                     Class Desc  \
0       $14.06  534813.0        2020-02-05  62-100 - S/s Basic Solid knit
1        $5.00  533479.0        2019-11-06     62-620 - L/s Fashion Knits
2            z  309417.0        2021-04-19          76-126 - Swim Bottoms
3            z  309419.0        2021-04-19          76-126 - Swim Bottoms
4  Grand Total       NaN               NaN                            NaN

        BRDNM                                       Product Name Retail Price  \
0         BKE                             BKE Burnout Dolman Top       $26.95
1     DAYTRIP                      Daytrip Eyelash Lace Trim Top       $25.00
2  Cyn & Luca  Cyn &#38; Luca Becky Ruched Reversible Swim Bo...       $24.95
3  Cyn & Luca  Cyn &#38; Luca Becky Ruched Reversible Swim Bo...       $24.95
4         NaN                                                NaN          NaN

  Sale Price   Cost Discount Desc  OH + OO  On Hand Current  \
0     $21.56  $7.50       20% off      1.0              1.0
1     $12.50  $7.50       50% off      NaN              NaN
2     $19.96  $7.00       20% off      1.0              1.0
3     $19.96  $7.00       20% off      NaN              NaN
4        NaN    NaN           NaN      2.0              2.0

   Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  SKU6 Count  \
0                     14.060                                 NaN         1.0
1                      5.000                                 NaN         NaN
2                     12.960                                 NaN         1.0
3                     12.960                                 NaN         NaN
4                     11.245                                 NaN         2.0

   SKU10 Count
0          1.0
1          NaN
2          1.0
3          NaN
4          2.0

In [31]:
WR1C_drop_receive_date = WR1C.dropna(subset=['Receive Date Last'])
WR1C_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$14.06,534813.0,2020-02-05,62-100 - S/s Basic Solid knit,BKE,BKE Burnout Dolman Top,$26.95,$21.56,$7.50,20% off,1.0,1.0,14.06,NaN,1.0,1.0
1,$5.00,533479.0,2019-11-06,62-620 - L/s Fashion Knits,DAYTRIP,Daytrip Eyelash Lace Trim Top,$25.00,$12.50,$7.50,50% off,NaN,NaN,5.00,NaN,NaN,NaN
2,z,309417.0,2021-04-19,76-126 - Swim Bottoms,Cyn & Luca,Cyn &#38; Luca Becky Ruched Reversible Swim Bo...,$24.95,$19.96,$7.00,20% off,1.0,1.0,12.96,NaN,1.0,1.0
3,z,309419.0,2021-04-19,76-126 - Swim Bottoms,Cyn & Luca,Cyn &#38; Luca Becky Ruched Reversible Swim Bo...,$24.95,$19.96,$7.00,20% off,NaN,NaN,12.96,NaN,NaN,NaN

## WR2
###  All DC
### ALL SKU Margin > 15.99
### OH & OO > 0 
### Last Receipt > 120 days ago
### Exclude 96

In [32]:
# Assign rule to dataframe
WR2 = dict_df.get("WR.2Gals(Reg) (>120)")
print(WR2)

           Margin       SKU Receive Date Last  \
0          $16.00  957505.0        2022-01-18
1          $16.00  542680.0        2021-12-30
2          $16.00  543763.0        2022-04-07
3          $16.00  542679.0        2021-12-30
4          $16.00  539558.0        2021-03-12
...           ...       ...               ...
7597       $99.70  963282.0        2022-03-28
7598       $99.74  947678.0        2022-11-22
7599       $99.82  949724.0        2018-11-13
7600       $99.90  967373.0        2022-10-10
7601  Grand Total       NaN               NaN

                              Class Desc        BRDNM  \
0                         91-100 - Belts          BKE
1           62-165 - Fashion Solid Tanks  FREE PEOPLE
2     62-105 - S/s 1/2 Slv casual novlty  FITZ + EDDI
3           62-165 - Fashion Solid Tanks  FREE PEOPLE
4                     62-175 - Tube Tops  FREE PEOPLE
...                                  ...          ...
7597              93-980 - Western Boots        ARIAT
7598           93-850 - Functional Boots   Dr Martens
7599         91-305 - Branded Sunglasses       Rayban
7600                 93-900 - Tall Boots  Azalea Wang
7601                                 NaN          NaN

                                        Product Name Retail Price Sale Price  \
0                              BKE Faux Leather Belt       $19.95     $19.95
1                Free People Mmkay Seamless Tank Top       $30.00     $30.00
2                         FITZ &#43; EDDI Ribbed Top       $22.00     $22.00
3                Free People Mmkay Seamless Tank Top       $30.00     $30.00
4                        Free People Carrie Tube Top       $30.00     $30.00
...                                              ...          ...        ...
7597  Ariat Blanket Dixon Western Leather Ankle Boot      $189.95    $189.95
7598                 Dr. Martens Pascal Leather Boot      $170.00    $170.00
7599        Ray-Ban&#174; Clubround Fleck Sunglasses      $180.00    $180.00
7600     Azalea Wang Texas Studded Tall Western Boot      $179.90    $179.90
7601                                             NaN          NaN        NaN

        Cost  Discount Desc  OH + OO  On Hand Current  \
0      $3.95            NaN      480              480
1     $14.00            NaN      248              248
2      $6.00            NaN      209              209
3     $14.00            NaN      158              158
4     $14.00            NaN      127              127
...      ...            ...      ...              ...
7597  $90.25            NaN      109              109
7598  $70.26            NaN      242              242
7599  $80.18            NaN        9                9
7600  $80.00            NaN      118               10
7601     NaN            NaN  1096323           972759

      Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  \
0                       16.0000                                 NaN
1                       16.0000                                 NaN
2                       16.0000                                 NaN
3                       16.0000                                 NaN
4                       16.0000                                 NaN
...                         ...                                 ...
7597                    99.7000                                 NaN
7598                    99.7400                                 NaN
7599                    99.8200                                 NaN
7600                    99.9000                               108.0
7601                    44.1614                            123564.0

      SKU6 Count  SKU10 Count
0            1.0            6
1            1.0            2
2            1.0            6
3            1.0            2
4            1.0            2
...          ...          ...
7597         1.0            9
7598         1.0            7
7599         1.0            1
7600         1.0            9
7601      7591.0        42699

[7602 rows x 16 columns]

In [33]:
WR2_drop_receive_date = WR2.dropna(subset=['Receive Date Last'])
WR2_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$16.00,957505.0,2022-01-18,91-100 - Belts,BKE,BKE Faux Leather Belt,$19.95,$19.95,$3.95,NaN,480,480,16.00,NaN,1.0,6
1,$16.00,542680.0,2021-12-30,62-165 - Fashion Solid Tanks,FREE PEOPLE,Free People Mmkay Seamless Tank Top,$30.00,$30.00,$14.00,NaN,248,248,16.00,NaN,1.0,2
2,$16.00,543763.0,2022-04-07,62-105 - S/s 1/2 Slv casual novlty,FITZ + EDDI,FITZ &#43; EDDI Ribbed Top,$22.00,$22.00,$6.00,NaN,209,209,16.00,NaN,1.0,6
3,$16.00,542679.0,2021-12-30,62-165 - Fashion Solid Tanks,FREE PEOPLE,Free People Mmkay Seamless Tank Top,$30.00,$30.00,$14.00,NaN,158,158,16.00,NaN,1.0,2
4,$16.00,539558.0,2021-03-12,62-175 - Tube Tops,FREE PEOPLE,Free People Carrie Tube Top,$30.00,$30.00,$14.00,NaN,127,127,16.00,NaN,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7596,$99.68,958172.0,2021-04-14,91-305 - Branded Sunglasses,Rayban,Ray-Ban&#174; Double Bridge Aviator Sunglasses,$174.00,$174.00,$74.32,NaN,1,1,99.68,NaN,1.0,1
7597,$99.70,963282.0,2022-03-28,93-980 - Western Boots,ARIAT,Ariat Blanket Dixon Western Leather Ankle Boot,$189.95,$189.95,$90.25,NaN,109,109,99.70,NaN,1.0,9
7598,$99.74,947678.0,2022-11-22,93-850 - Functional Boots,Dr Martens,Dr. Martens Pascal Leather Boot,$170.00,$170.00,$70.26,NaN,242,242,99.74,NaN,1.0,7
7599,$99.82,949724.0,2018-11-13,91-305 - Branded Sunglasses,Rayban,Ray-Ban&#174; Clubround Fleck Sunglasses,$180.00,$180.00,$80.18,NaN,9,9,99.82,NaN,1.0,1
7600,$99.90,967373.0,2022-10-10,93-900 - Tall Boots,Azalea Wang,Azalea Wang Texas Studded Tall Western Boot,$179.90,$179.90,$80.00,NaN,118,10,99.90,108.0,1.0,9

## WR3
### 91/100&150
### All SKU Margin > 12.99
### OH & OO > 0

In [34]:
# Assign rule to dataframe
WR3 = dict_df.get("WR3.Gals(Reg)91.100&150")
print(WR3)

          Margin       SKU Receive Date Last      Class Desc         BRDNM  \
0         $13.01  950290.0        2020-04-02  91-100 - Belts           BKE
1         $13.75  947098.0        2022-02-11  91-100 - Belts           BKE
2         $13.95  963081.0        2022-07-08  91-100 - Belts           BKE
3         $13.95  960711.0        2021-06-16  91-100 - Belts           BKE
4         $14.00  963628.0        2022-02-14  91-100 - Belts           BKE
..           ...       ...               ...             ...           ...
235       $48.20  968185.0        2023-02-22  91-100 - Belts  Rock Revival
236       $49.00  963463.0        2021-11-23  91-100 - Belts       Bed Stu
237       $49.00  968188.0        2022-10-05  91-100 - Belts       Bed Stu
238       $51.00  963462.0        2022-02-07  91-100 - Belts       Bed Stu
239  Grand Total       NaN               NaN             NaN           NaN

                                Product Name Retail Price Sale Price    Cost  \
0                        BKE Faux Suede Belt       $16.95     $16.95   $3.94
1                            BKE Concho Belt       $19.95     $19.95   $6.20
2                             BKE Basic Belt       $19.95     $19.95   $6.00
3                                BKE CC Belt       $19.95     $19.95   $6.00
4                        BKE Glitz Star Belt       $19.95     $19.95   $5.95
..                                       ...          ...        ...     ...
235          Rock Revival Glitz Leather Belt       $74.95     $74.95  $26.75
236               Bed Stu Proem Leather Belt       $89.00     $89.00  $40.00
237     Bed Stu Cut-Out Western Leather Belt       $89.00     $89.00  $40.00
238  Bed Stu Mohawk Embroidered Leather Belt       $89.00     $89.00  $38.00
239                                      NaN          NaN        NaN     NaN

     Discount Desc  OH + OO  On Hand Current  Average of Margin $ (LCM)  \
0              NaN       27               27                   13.01000
1              NaN       12               12                   13.75000
2              NaN      824              179                   13.95000
3              NaN        6                6                   13.95000
4              NaN        1                1                   14.00000
..             ...      ...              ...                        ...
235            NaN      453              453                   48.20000
236            NaN        6                6                   49.00000
237            NaN        5                5                   49.00000
238            NaN        4                4                   51.00000
239            NaN   147673            57299                   24.48113

     On Order (PO) All Stores and Dates  SKU6 Count  SKU10 Count
0                                   NaN         1.0            5
1                                   NaN         1.0            3
2                                 645.0         1.0            6
3                                   NaN         1.0            3
4                                   NaN         1.0            1
..                                  ...         ...          ...
235                                 NaN         1.0            4
236                                 NaN         1.0            3
237                                 NaN         1.0            4
238                                 NaN         1.0            3
239                             90374.0       209.0          890

[240 rows x 16 columns]

In [35]:
WR3_drop_receive_date = WR3.dropna(subset=['Receive Date Last'])
WR3_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$13.01,950290.0,2020-04-02,91-100 - Belts,BKE,BKE Faux Suede Belt,$16.95,$16.95,$3.94,NaN,27,27,13.01,NaN,1.0,5
1,$13.75,947098.0,2022-02-11,91-100 - Belts,BKE,BKE Concho Belt,$19.95,$19.95,$6.20,NaN,12,12,13.75,NaN,1.0,3
2,$13.95,963081.0,2022-07-08,91-100 - Belts,BKE,BKE Basic Belt,$19.95,$19.95,$6.00,NaN,824,179,13.95,645.0,1.0,6
3,$13.95,960711.0,2021-06-16,91-100 - Belts,BKE,BKE CC Belt,$19.95,$19.95,$6.00,NaN,6,6,13.95,NaN,1.0,3
4,$14.00,963628.0,2022-02-14,91-100 - Belts,BKE,BKE Glitz Star Belt,$19.95,$19.95,$5.95,NaN,1,1,14.00,NaN,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,$47.68,968145.0,2022-11-02,91-100 - Belts,Angel Ranch,Angel Ranch Western Fur Belt,$89.00,$89.00,$41.32,NaN,3,3,47.68,NaN,1.0,3
235,$48.20,968185.0,2023-02-22,91-100 - Belts,Rock Revival,Rock Revival Glitz Leather Belt,$74.95,$74.95,$26.75,NaN,453,453,48.20,NaN,1.0,4
236,$49.00,963463.0,2021-11-23,91-100 - Belts,Bed Stu,Bed Stu Proem Leather Belt,$89.00,$89.00,$40.00,NaN,6,6,49.00,NaN,1.0,3
237,$49.00,968188.0,2022-10-05,91-100 - Belts,Bed Stu,Bed Stu Cut-Out Western Leather Belt,$89.00,$89.00,$40.00,NaN,5,5,49.00,NaN,1.0,4
238,$51.00,963462.0,2022-02-07,91-100 - Belts,Bed Stu,Bed Stu Mohawk Embroidered Leather Belt,$89.00,$89.00,$38.00,NaN,4,4,51.00,NaN,1.0,3

## WR4
### 91/200, 205, 285
### NO BKE or BOUTIQUE BY BKE, BKE BOUTIQUE
### ALL SKU w Margin > 9.99
### OH & OO > 0

In [36]:
# Assign rule to dataframe
WR4 = dict_df.get("WR4.Gals(Reg)91 (200,205,285)")
print(WR4)

         Margin       SKU Receive Date Last                    Class Desc  \
0        $10.00  951613.0        2019-05-10   91-205 - Specialty Earrings
1        $10.00  956717.0        2020-05-20   91-205 - Specialty Earrings
2        $10.80  966438.0        2022-05-06   91-205 - Specialty Earrings
3        $10.80  966436.0        2022-05-06   91-205 - Specialty Earrings
4        $10.80  962007.0        2021-06-18  91-285 - Specialty Bracelets
5        $10.81  962543.0        2022-05-06   91-205 - Specialty Earrings
6        $10.88  961499.0        2022-05-06   91-205 - Specialty Earrings
7        $11.19  960985.0        2022-02-02  91-285 - Specialty Bracelets
8        $12.00  960980.0        2021-02-16   91-205 - Specialty Earrings
9        $13.20  957219.0        2020-06-12   91-205 - Specialty Earrings
10       $14.40  960995.0        2021-03-10  91-285 - Specialty Bracelets
11       $15.00  966440.0        2022-05-06   91-205 - Specialty Earrings
12       $15.00  961507.0        2021-09-02   91-205 - Specialty Earrings
13       $15.49  970746.0               NaN   91-205 - Specialty Earrings
14       $16.24  970742.0               NaN   91-205 - Specialty Earrings
15       $16.49  970744.0               NaN   91-205 - Specialty Earrings
16       $16.49  970743.0               NaN   91-205 - Specialty Earrings
17       $17.40  965820.0        2022-06-10  91-285 - Specialty Bracelets
18       $17.48  967493.0        2023-01-09  91-285 - Specialty Bracelets
19       $17.49  970745.0               NaN   91-205 - Specialty Earrings
20       $17.54  968815.0        2023-02-22   91-205 - Specialty Earrings
21       $17.57  966634.0        2023-01-09   91-205 - Specialty Earrings
22       $17.99  969031.0        2023-03-01   91-205 - Specialty Earrings
23       $18.53  965817.0        2022-06-10   91-205 - Specialty Earrings
24       $18.93  966635.0        2023-01-09   91-205 - Specialty Earrings
25       $18.95  965824.0        2022-06-09   91-205 - Specialty Earrings
26       $19.06  966158.0        2022-08-01   91-205 - Specialty Earrings
27       $19.55  966129.0        2022-09-28   91-205 - Specialty Earrings
28       $19.70  965826.0        2022-06-24   91-205 - Specialty Earrings
29       $19.95  967491.0        2022-10-28  91-285 - Specialty Bracelets
30       $19.95  965823.0        2022-08-16   91-205 - Specialty Earrings
31       $19.95  965825.0        2022-07-29   91-205 - Specialty Earrings
32       $19.99  969275.0        2023-02-22   91-205 - Specialty Earrings
33       $20.00  957559.0        2020-07-22  91-285 - Specialty Bracelets
34       $20.14  969219.0        2023-02-22  91-285 - Specialty Bracelets
35       $20.20  967303.0        2022-11-09   91-205 - Specialty Earrings
36       $20.37  966161.0        2022-08-01   91-205 - Specialty Earrings
37       $20.40  966208.0        2022-08-01   91-205 - Specialty Earrings
38       $20.44  966660.0        2022-09-01   91-205 - Specialty Earrings
39       $20.45  965827.0        2022-06-09  91-285 - Specialty Bracelets
40       $20.49  970907.0               NaN   91-205 - Specialty Earrings
41       $21.12  965810.0        2022-06-09  91-285 - Specialty Bracelets
42       $21.20  966630.0        2023-01-09  91-285 - Specialty Bracelets
43       $21.27  967488.0        2022-10-28   91-205 - Specialty Earrings
44       $21.65  966207.0        2022-08-25  91-285 - Specialty Bracelets
45       $21.95  966573.0        2022-08-24  91-285 - Specialty Bracelets
46       $21.95  967301.0        2022-11-09   91-205 - Specialty Earrings
47       $21.95  965821.0        2022-06-09   91-205 - Specialty Earrings
48       $21.99  969032.0        2023-03-01   91-205 - Specialty Earrings
49       $22.05  966126.0        2022-09-12   91-205 - Specialty Earrings
50       $22.10  966160.0        2022-08-01  91-285 - Specialty Bracelets
51       $22.17  966539.0        2022-08-24   91-205 - Specialty Earrings
52       $23.00  962580.0        2021-12-10   91-205 - Specialty Earrings
53       $23.58  966210.0        2022-08-01  91-285 - Specialty Bracelets
54       $24.37  966235.0        2022-08-08   91-205 - Specialty Earrings
55       $27.00  962585.0        2021-12-10  91-285 - Specialty Bracelets
56       $27.00  962583.0        2021-12-10  91-285 - Specialty Bracelets
57  Grand Total       NaN               NaN                           NaN

                    BRDNM                                       Product Name  \
0           Nichole Lewis     Nichole Lewis Designs Textured Leather Earring
1           Nichole Lewis     Nichole Lewis Designs Poppy Print Mini Earring
2            Groupie Love        Groupie Love&#174; Love Guitar Pick Earring
3            Groupie Love       Groupie Love&#174; Peace Guitar Pick Earring
4     Pura Vida Bracelets                       Pura Vida Neon Moon Bracelet
5            Groupie Love       Groupie Love&#174; Swirl Guitar Pick Earring
6            Groupie Love   Groupie Love&#174; Turquoise Guitar Pick Earring
7     Pura Vida Bracelets                      Pura Vida Mood Charm Bracelet
8     Pura Vida Bracelets                       Pura Vida Heart Hoop Earring
9   Grounded Goods Design          Grounded Goods Design Zebra Petal Earring
10    Pura Vida Bracelets                           Pura Vida Salty Bracelet
11           Groupie Love         Groupie Love&#174; ILY Guitar Pick Earring
12           Groupie Love    Groupie Love&#174; Engraved Guitar Pick Earring
13      STERLING & STITCH                                                NaN
14      STERLING & STITCH                                                NaN
15      STERLING & STITCH                                                NaN
16      STERLING & STITCH                                                NaN
17      STERLING & STITCH      Sterling &#38; Stitch Tooled Leather Bracelet
18      STERLING & STITCH     Sterling &#38; Stitch Western Stretch Bracelet
19      STERLING & STITCH                                                NaN
20      STERLING & STITCH  Sterling &#38; Stitch Cow Print Wood Drop Earring
21      STERLING & STITCH        Sterling &#38; Stitch Western Cross Earring
22      STERLING & STITCH         Sterling &#38; Stitch Metal Fringe Earring
23      STERLING & STITCH          Sterling &#38; Stitch Fringe Drop Earring
24      STERLING & STITCH  Sterling &#38; Stitch Turquoise Statement Earring
25      STERLING & STITCH             Sterling &#38; Stitch Longhorn Earring
26      STERLING & STITCH  Sterling &#38; Stitch Statement Turquoise Earring
27      STERLING & STITCH      Sterling &#38; Stitch Statement Steer Earring
28      STERLING & STITCH    Sterling &#38; Stitch Southwestern Wood Earring
29      STERLING & STITCH   Sterling &#38; Stitch Statement Stretch Bracelet
30      STERLING & STITCH             Sterling &#38; Stitch Embossed Earring
31      STERLING & STITCH    Sterling &#38; Stitch Southwestern Drop Earring
32      STERLING & STITCH  Sterling &#38; Stitch Western Fringe Drop Earring
33          Keep It Gypsy     Keep It Gypsy Studded Cowhide Leather Bracelet
34      STERLING & STITCH   Sterling &#38; Stitch Western Statement Bracelet
35      STERLING & STITCH      Sterling &#38; Stitch Fringe Teardrop Earring
36      STERLING & STITCH        Sterling &#38; Stitch Embossed Star Earring
37      STERLING & STITCH        Sterling &#38; Stitch Colored Stone Earring
38      STERLING & STITCH      Sterling &#38; Stitch Turquoise Metal Earring
39      STERLING & STITCH  Sterling &#38; Stitch Turquoise Statement Brac...
40      STERLING & STITCH                                                NaN
41      STERLING & STITCH     Sterling &#38; Stitch Turquoise Stone Bracelet
42      STERLING & STITCH  Sterling &#38; Stitch Turquoise Statement Brac...
43      STERLING & STITCH    Sterling &#38; Stitch Western Statement Earring
44      STERLING & STITCH     Sterling &#38; Stitch Stone Statement Bracelet
45      STERLING & STITCH      Sterling &#38; Stitch Squash Blossom Bracelet
46      STERLING & STITCH    Sterling &#38; Stitch Rhinestone Fringe Earring
47      STERLING & STITCH  Sterling &#38; Stitch Southwestern Fringe Earring
48      STERLING & STITCH  Sterling &#38; Stitch 6 Pack Western Stud Earr...
49      STERLING & STITCH     Sterling &#38; Stitch Statement Fringe Earring
50      STERLING & STITCH  Sterling &#38; Stitch 3 Pack Stretch Bracelet Set
51      STERLING & STITCH       Sterling &#38; Stitch Squash Blossom Earring
52  Sahira Jewelry Design            Sahira Jewelry Design Zoey Hoop Earring
53      STERLING & STITCH  Sterling &#38; Stitch Turquoise Statement Brac...
54      STERLING & STITCH   Sterling &#38; Stitch 3 Pack Howlite Earring Set
55  Sahira Jewelry Design        Sahira Jewelry Design Frankie Link Bracelet
56  Sahira Jewelry Design      Sahira Jewelry Design Elsie Eternity Bracelet
57                    NaN                                                NaN

   Retail Price Sale Price    Cost  Discount Desc  OH + OO  On Hand Current  \
0        $15.00     $15.00   $5.00            NaN       22               22
1        $15.00     $15.00   $5.00            NaN       18               18
2        $18.00     $18.00   $7.20            NaN       14               14
3        $18.00     $18.00   $7.20            NaN        5                5
4        $18.00     $18.00   $7.20            NaN        4                4
5        $18.00     $18.00   $7.19            NaN        1                1
6        $18.00     $18.00   $7.12            NaN        1                1
7        $16.00     $16.00   $4.81            NaN        5                5
8        $20.00     $20.00   $8.00            NaN        1                1
9        $22.00     $22.00   $8.80            NaN        8                8
10       $24.00     $24.00   $9.60            NaN        3                3
11       $25.00     $25.00  $10.00            NaN       19               19
12       $25.00     $25.00  $10.00            NaN        2                2
13       $19.99     $19.99   $4.50            NaN      360                0
14       $19.99     $19.99   $3.75            NaN      600                0
15       $19.99     $19.99   $3.50            NaN      360                0
16       $19.99     $19.99   $3.50            NaN      600                0
17       $24.95     $24.95   $7.55            NaN        1                1
18       $24.95     $24.95   $7.47            NaN      689              689
19       $19.99     $19.99   $2.50            NaN      360                0
20       $19.99     $19.99   $2.45            NaN      826              826
21       $19.95     $19.95   $2.38            NaN      540              540
22       $22.99     $22.99   $5.00            NaN      566              566
23       $22.95     $22.95   $4.42            NaN       31               31
24       $22.95     $22.95   $4.02            NaN      604              604
25       $22.95     $22.95   $4.00            NaN        2                2
26       $22.95     $22.95   $3.89            NaN       79               79
27       $22.95     $22.95   $3.40            NaN       41               41
28       $22.95     $22.95   $3.25            NaN        1                1
29       $26.95     $26.95   $7.00            NaN      289              289
30       $22.95     $22.95   $3.00            NaN       87               87
31       $22.95     $22.95   $3.00            NaN        2                2
32       $22.99     $22.99   $3.00            NaN      537              537
33       $30.00     $30.00  $10.00            NaN       26               26
34       $24.99     $24.99   $4.85            NaN      531              531
35       $24.95     $24.95   $4.75            NaN      459              459
36       $22.95     $22.95   $2.58            NaN      270              270
37       $24.95     $24.95   $4.55            NaN       45               45
38       $24.95     $24.95   $4.51            NaN       15               15
39       $26.95     $26.95   $6.50            NaN       50               50
40       $24.99     $24.99   $4.50            NaN      600                0
41       $26.95     $26.95   $5.83            NaN       21               21
42       $26.95     $26.95   $5.75            NaN      575              575
43       $24.95     $24.95   $3.68            NaN      197              197
44       $29.95     $29.95   $8.30            NaN      298              298
45       $26.95     $26.95   $5.00            NaN      745              745
46       $26.95     $26.95   $5.00            NaN      278              278
47       $26.95     $26.95   $5.00            NaN       72               72
48       $29.99     $29.99   $8.00            NaN      825              825
49       $26.95     $26.95   $4.90            NaN      148              148
50       $26.95     $26.95   $4.85            NaN       35               35
51       $24.95     $24.95   $2.78            NaN      498              498
52       $39.00     $39.00  $16.00            NaN        2                2
53       $29.95     $29.95   $6.37            NaN      167              167
54       $26.95     $26.95   $2.58            NaN      234              234
55       $49.00     $49.00  $22.00            NaN        2                2
56       $49.00     $49.00  $22.00            NaN        1                1
57          NaN        NaN     NaN            NaN    12772             9892

    Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  SKU6 Count  \
0                   10.000000                                 NaN         1.0
1                   10.000000                                 NaN         1.0
2                   10.800000                                 NaN         1.0
3                   10.800000                                 NaN         1.0
4                   10.800000                                 NaN         1.0
5                   10.810000                                 NaN         1.0
6                   10.880000                                 NaN         1.0
7                   11.190000                                 NaN         1.0
8                   12.000000                                 NaN         1.0
9                   13.200000                                 NaN         1.0
10                  14.400000                                 NaN         1.0
11                  15.000000                                 NaN         1.0
12                  15.000000                                 NaN         1.0
13                  15.490000                               360.0         NaN
14                  16.240000                               600.0         NaN
15                  16.490000                               360.0         NaN
16                  16.490000                               600.0         NaN
17                  17.400000                                 NaN         1.0
18                  17.480000                                 NaN         1.0
19                  17.490000                               360.0         NaN
20                  17.540000                                 NaN         1.0
21                  17.570000                                 NaN         1.0
22                  17.990000                                 NaN         1.0
23                  18.530000                                 NaN         1.0
24                  18.930000                                 NaN         1.0
25                  18.950000                                 NaN         1.0
26                  19.060000                                 NaN         1.0
27                  19.550000                                 NaN         1.0
28                  19.700000                                 NaN         1.0
29                  19.950000                                 NaN         1.0
30                  19.950000                                 NaN         1.0
31                  19.950000                                 NaN         1.0
32                  19.990000                                 NaN         1.0
33                  20.000000                                 NaN         1.0
34                  20.140000                                 NaN         1.0
35                  20.200000                                 NaN         1.0
36                  20.370000                                 NaN         1.0
37                  20.400000                                 NaN         1.0
38                  20.440000                                 NaN         1.0
39                  20.450000                                 NaN         1.0
40                  20.490000                               600.0         NaN
41                  21.120000                                 NaN         1.0
42                  21.200000                                 NaN         1.0
43                  21.270000                                 NaN         1.0
44                  21.650000                                 NaN         1.0
45                  21.950000                                 NaN         1.0
46                  21.950000                                 NaN         1.0
47                  21.950000                                 NaN         1.0
48                  21.990000                                 NaN         1.0
49                  22.050000                                 NaN         1.0
50                  22.100000                                 NaN         1.0
51                  22.170000                                 NaN         1.0
52                  23.000000                                 NaN         1.0
53                  23.580000                                 NaN         1.0
54                  24.370000                                 NaN         1.0
55                  27.000000                                 NaN         1.0
56                  27.000000                                 NaN         1.0
57                  18.358947                              2880.0        51.0

    SKU10 Count
0             1
1             1
2             1
3             1
4             1
5             1
6             1
7             1
8             1
9             1
10            1
11            1
12            1
13            1
14            1
15            1
16            1
17            1
18            1
19            1
20            1
21            1
22            1
23            1
24            1
25            1
26            1
27            1
28            1
29            1
30            1
31            1
32            1
33            1
34            1
35            1
36            1
37            1
38            1
39            1
40            1
41            1
42            1
43            1
44            1
45            1
46            1
47            1
48            1
49            1
50            1
51            1
52            1
53            1
54            1
55            1
56            1
57           57

In [37]:
WR4_drop_receive_date = WR4.dropna(subset=['Receive Date Last'])
WR4_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$10.00,951613.0,2019-05-10,91-205 - Specialty Earrings,Nichole Lewis,Nichole Lewis Designs Textured Leather Earring,$15.00,$15.00,$5.00,NaN,22,22,10.00,NaN,1.0,1
1,$10.00,956717.0,2020-05-20,91-205 - Specialty Earrings,Nichole Lewis,Nichole Lewis Designs Poppy Print Mini Earring,$15.00,$15.00,$5.00,NaN,18,18,10.00,NaN,1.0,1
2,$10.80,966438.0,2022-05-06,91-205 - Specialty Earrings,Groupie Love,Groupie Love&#174; Love Guitar Pick Earring,$18.00,$18.00,$7.20,NaN,14,14,10.80,NaN,1.0,1
3,$10.80,966436.0,2022-05-06,91-205 - Specialty Earrings,Groupie Love,Groupie Love&#174; Peace Guitar Pick Earring,$18.00,$18.00,$7.20,NaN,5,5,10.80,NaN,1.0,1
4,$10.80,962007.0,2021-06-18,91-285 - Specialty Bracelets,Pura Vida Bracelets,Pura Vida Neon Moon Bracelet,$18.00,$18.00,$7.20,NaN,4,4,10.80,NaN,1.0,1
5,$10.81,962543.0,2022-05-06,91-205 - Specialty Earrings,Groupie Love,Groupie Love&#174; Swirl Guitar Pick Earring,$18.00,$18.00,$7.19,NaN,1,1,10.81,NaN,1.0,1
6,$10.88,961499.0,2022-05-06,91-205 - Specialty Earrings,Groupie Love,Groupie Love&#174; Turquoise Guitar Pick Earring,$18.00,$18.00,$7.12,NaN,1,1,10.88,NaN,1.0,1
7,$11.19,960985.0,2022-02-02,91-285 - Specialty Bracelets,Pura Vida Bracelets,Pura Vida Mood Charm Bracelet,$16.00,$16.00,$4.81,NaN,5,5,11.19,NaN,1.0,1
8,$12.00,960980.0,2021-02-16,91-205 - Specialty Earrings,Pura Vida Bracelets,Pura Vida Heart Hoop Earring,$20.00,$20.00,$8.00,NaN,1,1,12.00,NaN,1.0,1
9,$13.20,957219.0,2020-06-12,91-205 - Specialty Earrings,Grounded Goods Design,Grounded Goods Design Zebra Petal Earring,$22.00,$22.00,$8.80,NaN,8,8,13.20,NaN,1.0,1
10,$14.40,960995.0,2021-03-10,91-285 - Specialty Bracelets,Pura Vida Bracelets,Pura Vida Salty Bracelet,$24.00,$24.00,$9.60,NaN,3,3,14.40,NaN,1.0,1
11,$15.00,966440.0,2022-05-06,91-205 - Specialty Earrings,Groupie Love,Groupie Love&#174; ILY Guitar Pick Earring,$25.00,$25.00,$10.00,NaN,19,19,15.00,NaN,1.0,1
12,$15.00,961507.0,2021-09-02,91-205 - Specialty Earrings,Groupie Love,Groupie Love&#174; Engraved Guitar Pick Earring,$25.00,$25.00,$10.00,NaN,2,2,15.00,NaN,1.0,1
17,$17.40,965820.0,2022-06-10,91-285 - Specialty Bracelets,STERLING & STITCH,Sterling &#38; Stitch Tooled Leather Bracelet,$24.95,$24.95,$7.55,NaN,1,1,17.40,NaN,1.0,1
18,$17.48,967493.0,2023-01-09,91-285 - Specialty Bracelets,STERLING & STITCH,Sterling &#38; Stitch Western Stretch Bracelet,$24.95,$24.95,$7.47,NaN,689,689,17.48,NaN,1.0,1
20,$17.54,968815.0,2023-02-22,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Cow Print Wood Drop Earring,$19.99,$19.99,$2.45,NaN,826,826,17.54,NaN,1.0,1
21,$17.57,966634.0,2023-01-09,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Western Cross Earring,$19.95,$19.95,$2.38,NaN,540,540,17.57,NaN,1.0,1
22,$17.99,969031.0,2023-03-01,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Metal Fringe Earring,$22.99,$22.99,$5.00,NaN,566,566,17.99,NaN,1.0,1
23,$18.53,965817.0,2022-06-10,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Fringe Drop Earring,$22.95,$22.95,$4.42,NaN,31,31,18.53,NaN,1.0,1
24,$18.93,966635.0,2023-01-09,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Turquoise Statement Earring,$22.95,$22.95,$4.02,NaN,604,604,18.93,NaN,1.0,1
25,$18.95,965824.0,2022-06-09,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Longhorn Earring,$22.95,$22.95,$4.00,NaN,2,2,18.95,NaN,1.0,1
26,$19.06,966158.0,2022-08-01,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Statement Turquoise Earring,$22.95,$22.95,$3.89,NaN,79,79,19.06,NaN,1.0,1
27,$19.55,966129.0,2022-09-28,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Statement Steer Earring,$22.95,$22.95,$3.40,NaN,41,41,19.55,NaN,1.0,1
28,$19.70,965826.0,2022-06-24,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Southwestern Wood Earring,$22.95,$22.95,$3.25,NaN,1,1,19.70,NaN,1.0,1
29,$19.95,967491.0,2022-10-28,91-285 - Specialty Bracelets,STERLING & STITCH,Sterling &#38; Stitch Statement Stretch Bracelet,$26.95,$26.95,$7.00,NaN,289,289,19.95,NaN,1.0,1
30,$19.95,965823.0,2022-08-16,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Embossed Earring,$22.95,$22.95,$3.00,NaN,87,87,19.95,NaN,1.0,1
31,$19.95,965825.0,2022-07-29,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Southwestern Drop Earring,$22.95,$22.95,$3.00,NaN,2,2,19.95,NaN,1.0,1
32,$19.99,969275.0,2023-02-22,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Western Fringe Drop Earring,$22.99,$22.99,$3.00,NaN,537,537,19.99,NaN,1.0,1
33,$20.00,957559.0,2020-07-22,91-285 - Specialty Bracelets,Keep It Gypsy,Keep It Gypsy Studded Cowhide Leather Bracelet,$30.00,$30.00,$10.00,NaN,26,26,20.00,NaN,1.0,1
34,$20.14,969219.0,2023-02-22,91-285 - Specialty Bracelets,STERLING & STITCH,Sterling &#38; Stitch Western Statement Bracelet,$24.99,$24.99,$4.85,NaN,531,531,20.14,NaN,1.0,1
35,$20.20,967303.0,2022-11-09,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Fringe Teardrop Earring,$24.95,$24.95,$4.75,NaN,459,459,20.20,NaN,1.0,1
36,$20.37,966161.0,2022-08-01,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Embossed Star Earring,$22.95,$22.95,$2.58,NaN,270,270,20.37,NaN,1.0,1
37,$20.40,966208.0,2022-08-01,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Colored Stone Earring,$24.95,$24.95,$4.55,NaN,45,45,20.40,NaN,1.0,1
38,$20.44,966660.0,2022-09-01,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Turquoise Metal Earring,$24.95,$24.95,$4.51,NaN,15,15,20.44,NaN,1.0,1
39,$20.45,965827.0,2022-06-09,91-285 - Specialty Bracelets,STERLING & STITCH,Sterling &#38; Stitch Turquoise Statement Brac...,$26.95,$26.95,$6.50,NaN,50,50,20.45,NaN,1.0,1
41,$21.12,965810.0,2022-06-09,91-285 - Specialty Bracelets,STERLING & STITCH,Sterling &#38; Stitch Turquoise Stone Bracelet,$26.95,$26.95,$5.83,NaN,21,21,21.12,NaN,1.0,1
42,$21.20,966630.0,2023-01-09,91-285 - Specialty Bracelets,STERLING & STITCH,Sterling &#38; Stitch Turquoise Statement Brac...,$26.95,$26.95,$5.75,NaN,575,575,21.20,NaN,1.0,1
43,$21.27,967488.0,2022-10-28,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Western Statement Earring,$24.95,$24.95,$3.68,NaN,197,197,21.27,NaN,1.0,1
44,$21.65,966207.0,2022-08-25,91-285 - Specialty Bracelets,STERLING & STITCH,Sterling &#38; Stitch Stone Statement Bracelet,$29.95,$29.95,$8.30,NaN,298,298,21.65,NaN,1.0,1
45,$21.95,966573.0,2022-08-24,91-285 - Specialty Bracelets,STERLING & STITCH,Sterling &#38; Stitch Squash Blossom Bracelet,$26.95,$26.95,$5.00,NaN,745,745,21.95,NaN,1.0,1
46,$21.95,967301.0,2022-11-09,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Rhinestone Fringe Earring,$26.95,$26.95,$5.00,NaN,278,278,21.95,NaN,1.0,1
47,$21.95,965821.0,2022-06-09,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Southwestern Fringe Earring,$26.95,$26.95,$5.00,NaN,72,72,21.95,NaN,1.0,1
48,$21.99,969032.0,2023-03-01,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch 6 Pack Western Stud Earr...,$29.99,$29.99,$8.00,NaN,825,825,21.99,NaN,1.0,1
49,$22.05,966126.0,2022-09-12,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Statement Fringe Earring,$26.95,$26.95,$4.90,NaN,148,148,22.05,NaN,1.0,1
50,$22.10,966160.0,2022-08-01,91-285 - Specialty Bracelets,STERLING & STITCH,Sterling &#38; Stitch 3 Pack Stretch Bracelet Set,$26.95,$26.95,$4.85,NaN,35,35,22.10,NaN,1.0,1
51,$22.17,966539.0,2022-08-24,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch Squash Blossom Earring,$24.95,$24.95,$2.78,NaN,498,498,22.17,NaN,1.0,1
52,$23.00,962580.0,2021-12-10,91-205 - Specialty Earrings,Sahira Jewelry Design,Sahira Jewelry Design Zoey Hoop Earring,$39.00,$39.00,$16.00,NaN,2,2,23.00,NaN,1.0,1
53,$23.58,966210.0,2022-08-01,91-285 - Specialty Bracelets,STERLING & STITCH,Sterling &#38; Stitch Turquoise Statement Brac...,$29.95,$29.95,$6.37,NaN,167,167,23.58,NaN,1.0,1
54,$24.37,966235.0,2022-08-08,91-205 - Specialty Earrings,STERLING & STITCH,Sterling &#38; Stitch 3 Pack Howlite Earring Set,$26.95,$26.95,$2.58,NaN,234,234,24.37,NaN,1.0,1
55,$27.00,962585.0,2021-12-10,91-285 - Specialty Bracelets,Sahira Jewelry Design,Sahira Jewelry Design Frankie Link Bracelet,$49.00,$49.00,$22.00,NaN,2,2,27.00,NaN,1.0,1
56,$27.00,962583.0,2021-12-10,91-285 - Specialty Bracelets,Sahira Jewelry Design,Sahira Jewelry Design Elsie Eternity Bracelet,$49.00,$49.00,$22.00,NaN,1,1,27.00,NaN,1.0,1

## WR5
### 91/800, 810, 815
### ALL SKU with Margin > 15.94 
### OH & OO > 0

In [38]:
# Assign rule to dataframe
WR5 = dict_df.get("WR5.Gals(REG)800.810.815")
print(WR5)

         Margin       SKU Receive Date Last                       Class Desc  \
0        $16.20  964110.0        2022-11-23        91-810 - Hats - Cold wthr
1        $16.20  964109.0        2022-10-04        91-810 - Hats - Cold wthr
2        $16.35  966795.0        2022-11-11        91-810 - Hats - Cold wthr
3        $16.45  967047.0        2022-10-28   91-815 - Gloves - Cold weather
4        $16.46  953034.0        2022-10-28   91-815 - Gloves - Cold weather
5        $16.51  957841.0        2022-10-27   91-815 - Gloves - Cold weather
6        $16.55  957800.0        2022-10-03        91-810 - Hats - Cold wthr
7        $16.65  966796.0        2022-11-28        91-810 - Hats - Cold wthr
8        $16.75  966793.0        2022-11-10        91-810 - Hats - Cold wthr
9        $16.95  966794.0        2022-11-29        91-810 - Hats - Cold wthr
10       $16.95  966787.0        2022-10-13        91-810 - Hats - Cold wthr
11       $16.95  966799.0        2022-10-13        91-810 - Hats - Cold wthr
12       $16.95  962836.0        2021-11-16  91-800 - Scarves - Cold weather
13       $16.95  962827.0        2021-11-10        91-810 - Hats - Cold wthr
14       $16.95  960028.0        2020-11-06        91-810 - Hats - Cold wthr
15       $16.95  962824.0        2021-11-24        91-810 - Hats - Cold wthr
16       $16.95  962817.0        2021-10-07        91-810 - Hats - Cold wthr
17       $16.95  962818.0        2021-10-07        91-810 - Hats - Cold wthr
18       $17.20  966785.0        2022-09-22        91-810 - Hats - Cold wthr
19       $17.20  966792.0        2022-11-10        91-810 - Hats - Cold wthr
20       $17.45  962823.0        2021-11-16        91-810 - Hats - Cold wthr
21       $17.70  966255.0        2022-10-13        91-810 - Hats - Cold wthr
22       $17.95  962834.0        2021-11-10  91-800 - Scarves - Cold weather
23       $17.95  966791.0        2022-11-02        91-810 - Hats - Cold wthr
24       $17.95  966719.0        2022-11-11  91-800 - Scarves - Cold weather
25       $17.95  957805.0        2021-10-22        91-810 - Hats - Cold wthr
26       $18.45  966718.0        2022-10-10  91-800 - Scarves - Cold weather
27       $18.62  966798.0        2022-10-13  91-800 - Scarves - Cold weather
28       $18.93  966789.0        2022-10-13        91-810 - Hats - Cold wthr
29       $21.19  963135.0        2021-12-02        91-810 - Hats - Cold wthr
30       $21.95  966797.0        2022-10-13  91-800 - Scarves - Cold weather
31       $22.09  957815.0        2022-11-10  91-800 - Scarves - Cold weather
32       $23.28  967116.0        2022-10-26  91-800 - Scarves - Cold weather
33  Grand Total       NaN               NaN                              NaN

            BRDNM                         Product Name Retail Price  \
0              CC             C.C&#174; Printed Beanie       $24.95
1              CC             C.C&#174; Printed Beanie       $24.95
2              CC        C.C&#174; Faux Fur Pom Beanie       $24.95
3              CC          C.C&#174; Checkered Mittens       $24.95
4              CC   C.C&#174; Solid Convertible Mitten       $24.95
5              CC  C.C&#174; Solid Convertible Mittens       $24.95
6              CC        C.C&#174; Faux Fur Pom Beanie       $24.95
7              CC         C.C&#174; Chunky Knit Beanie       $24.95
8              CC        C.C&#174; Faux Fur Pom Beanie       $24.95
9              CC           C.C&#174; Patterned Beanie       $24.95
10             CC              C.C&#174; Ribbed Beanie       $24.95
11             CC              C.C&#174; Sequin Beanie       $24.95
12             CC      C.C&#174; Ribbed Infinity Scarf       $24.95
13             CC          C.C&#174; Cable Knit Beanie       $24.95
14     KW Fashion               Color Block Pom Beanie       $24.95
15             CC              C.C&#174; Sequin Beanie       $24.95
16             CC        C.C&#174; Faux Fur Pom Beanie       $24.95
17             CC          C.C&#174; Cable Knit Beanie       $24.95
18             CC         C.C&#174; Wide Ribbed Beanie       $24.95
19             CC              C.C&#174; Ribbed Beanie       $24.95
20             CC  C.C&#174; Cheetah Print Knit Beanie       $24.95
21        O'Neill         O&#39;Neill Groceries Beanie       $29.50
22             CC          C.C&#174; Ribbed Knit Scarf       $29.95
23             CC       C.C&#174;  Faux Fur Pom Beanie       $24.95
24  David & Young      David & Young Plaid Fring Scarf       $24.95
25             CC      C.C&#174; Cable Knit Pom Beanie       $24.95
26  David & Young            David & Young Plaid Scarf       $24.95
27             CC       C.C&#174; Classic Ribbed Scarf       $29.95
28             CC                 C.C&#174; Pom Beanie       $24.95
29            BKE                BKE Fuzzy Knit Beanie       $24.95
30             CC        C.C&#174; Sequin Ribbed Scarf       $34.95
31             CC          C.C&#174; Boucle Yarn Scarf       $29.95
32            BKE             BKE Blanket Fringe Scarf       $34.95
33            NaN                                  NaN          NaN

   Sale Price    Cost  Discount Desc  OH + OO  On Hand Current  \
0      $24.95   $8.75            NaN       72               72
1      $24.95   $8.75            NaN        5                5
2      $24.95   $8.60            NaN       25               25
3      $24.95   $8.50            NaN      121              121
4      $24.95   $8.49            NaN        3                3
5      $24.95   $8.44            NaN       40               40
6      $24.95   $8.40            NaN        3                3
7      $24.95   $8.30            NaN      528              528
8      $24.95   $8.20            NaN      364              364
9      $24.95   $8.00            NaN      414              414
10     $24.95   $8.00            NaN      168              168
11     $24.95   $8.00            NaN      168              168
12     $24.95   $8.00            NaN       61               61
13     $24.95   $8.00            NaN        4                4
14     $24.95   $8.00            NaN        1                1
15     $24.95   $8.00            NaN        1                1
16     $24.95   $8.00            NaN        1                1
17     $24.95   $8.00            NaN        1                1
18     $24.95   $7.75            NaN      124              124
19     $24.95   $7.75            NaN       87               87
20     $24.95   $7.50            NaN       12               12
21     $29.50  $11.80            NaN        2                2
22     $29.95  $12.00            NaN      186              186
23     $24.95   $7.00            NaN      159              159
24     $24.95   $7.00            NaN      140              140
25     $24.95   $7.00            NaN        1                1
26     $24.95   $6.50            NaN      158              158
27     $29.95  $11.33            NaN      173              173
28     $24.95   $6.02            NaN      133              133
29     $24.95   $3.76            NaN      109              109
30     $34.95  $13.00            NaN      153              153
31     $29.95   $7.86            NaN      151              151
32     $34.95  $11.67            NaN      319              319
33        NaN     NaN            NaN     3887             3887

    Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  SKU6 Count  \
0                   16.200000                                 NaN           1
1                   16.200000                                 NaN           1
2                   16.350000                                 NaN           1
3                   16.450000                                 NaN           1
4                   16.460000                                 NaN           1
5                   16.510000                                 NaN           1
6                   16.550000                                 NaN           1
7                   16.650000                                 NaN           1
8                   16.750000                                 NaN           1
9                   16.950000                                 NaN           1
10                  16.950000                                 NaN           1
11                  16.950000                                 NaN           1
12                  16.950000                                 NaN           1
13                  16.950000                                 NaN           1
14                  16.950000                                 NaN           1
15                  16.950000                                 NaN           1
16                  16.950000                                 NaN           1
17                  16.950000                                 NaN           1
18                  17.200000                                 NaN           1
19                  17.200000                                 NaN           1
20                  17.450000                                 NaN           1
21                  17.700000                                 NaN           1
22                  17.950000                                 NaN           1
23                  17.950000                                 NaN           1
24                  17.950000                                 NaN           1
25                  17.950000                                 NaN           1
26                  18.450000                                 NaN           1
27                  18.620000                                 NaN           1
28                  18.930000                                 NaN           1
29                  21.190000                                 NaN           1
30                  21.950000                                 NaN           1
31                  22.090000                                 NaN           1
32                  23.280000                                 NaN           1
33                  17.773636                                 NaN          33

    SKU10 Count
0             1
1             1
2             1
3             1
4             1
5             1
6             1
7             1
8             1
9             1
10            1
11            1
12            1
13            1
14            1
15            1
16            1
17            1
18            1
19            1
20            1
21            1
22            1
23            1
24            1
25            1
26            1
27            1
28            1
29            1
30            1
31            1
32            1
33           33

In [39]:
WR5_drop_receive_date = WR5.dropna(subset=['Receive Date Last'])
WR5_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$16.20,964110.0,2022-11-23,91-810 - Hats - Cold wthr,CC,C.C&#174; Printed Beanie,$24.95,$24.95,$8.75,NaN,72,72,16.20,NaN,1,1
1,$16.20,964109.0,2022-10-04,91-810 - Hats - Cold wthr,CC,C.C&#174; Printed Beanie,$24.95,$24.95,$8.75,NaN,5,5,16.20,NaN,1,1
2,$16.35,966795.0,2022-11-11,91-810 - Hats - Cold wthr,CC,C.C&#174; Faux Fur Pom Beanie,$24.95,$24.95,$8.60,NaN,25,25,16.35,NaN,1,1
3,$16.45,967047.0,2022-10-28,91-815 - Gloves - Cold weather,CC,C.C&#174; Checkered Mittens,$24.95,$24.95,$8.50,NaN,121,121,16.45,NaN,1,1
4,$16.46,953034.0,2022-10-28,91-815 - Gloves - Cold weather,CC,C.C&#174; Solid Convertible Mitten,$24.95,$24.95,$8.49,NaN,3,3,16.46,NaN,1,1
5,$16.51,957841.0,2022-10-27,91-815 - Gloves - Cold weather,CC,C.C&#174; Solid Convertible Mittens,$24.95,$24.95,$8.44,NaN,40,40,16.51,NaN,1,1
6,$16.55,957800.0,2022-10-03,91-810 - Hats - Cold wthr,CC,C.C&#174; Faux Fur Pom Beanie,$24.95,$24.95,$8.40,NaN,3,3,16.55,NaN,1,1
7,$16.65,966796.0,2022-11-28,91-810 - Hats - Cold wthr,CC,C.C&#174; Chunky Knit Beanie,$24.95,$24.95,$8.30,NaN,528,528,16.65,NaN,1,1
8,$16.75,966793.0,2022-11-10,91-810 - Hats - Cold wthr,CC,C.C&#174; Faux Fur Pom Beanie,$24.95,$24.95,$8.20,NaN,364,364,16.75,NaN,1,1
9,$16.95,966794.0,2022-11-29,91-810 - Hats - Cold wthr,CC,C.C&#174; Patterned Beanie,$24.95,$24.95,$8.00,NaN,414,414,16.95,NaN,1,1
10,$16.95,966787.0,2022-10-13,91-810 - Hats - Cold wthr,CC,C.C&#174; Ribbed Beanie,$24.95,$24.95,$8.00,NaN,168,168,16.95,NaN,1,1
11,$16.95,966799.0,2022-10-13,91-810 - Hats - Cold wthr,CC,C.C&#174; Sequin Beanie,$24.95,$24.95,$8.00,NaN,168,168,16.95,NaN,1,1
12,$16.95,962836.0,2021-11-16,91-800 - Scarves - Cold weather,CC,C.C&#174; Ribbed Infinity Scarf,$24.95,$24.95,$8.00,NaN,61,61,16.95,NaN,1,1
13,$16.95,962827.0,2021-11-10,91-810 - Hats - Cold wthr,CC,C.C&#174; Cable Knit Beanie,$24.95,$24.95,$8.00,NaN,4,4,16.95,NaN,1,1
14,$16.95,960028.0,2020-11-06,91-810 - Hats - Cold wthr,KW Fashion,Color Block Pom Beanie,$24.95,$24.95,$8.00,NaN,1,1,16.95,NaN,1,1
15,$16.95,962824.0,2021-11-24,91-810 - Hats - Cold wthr,CC,C.C&#174; Sequin Beanie,$24.95,$24.95,$8.00,NaN,1,1,16.95,NaN,1,1
16,$16.95,962817.0,2021-10-07,91-810 - Hats - Cold wthr,CC,C.C&#174; Faux Fur Pom Beanie,$24.95,$24.95,$8.00,NaN,1,1,16.95,NaN,1,1
17,$16.95,962818.0,2021-10-07,91-810 - Hats - Cold wthr,CC,C.C&#174; Cable Knit Beanie,$24.95,$24.95,$8.00,NaN,1,1,16.95,NaN,1,1
18,$17.20,966785.0,2022-09-22,91-810 - Hats - Cold wthr,CC,C.C&#174; Wide Ribbed Beanie,$24.95,$24.95,$7.75,NaN,124,124,17.20,NaN,1,1
19,$17.20,966792.0,2022-11-10,91-810 - Hats - Cold wthr,CC,C.C&#174; Ribbed Beanie,$24.95,$24.95,$7.75,NaN,87,87,17.20,NaN,1,1
20,$17.45,962823.0,2021-11-16,91-810 - Hats - Cold wthr,CC,C.C&#174; Cheetah Print Knit Beanie,$24.95,$24.95,$7.50,NaN,12,12,17.45,NaN,1,1
21,$17.70,966255.0,2022-10-13,91-810 - Hats - Cold wthr,O'Neill,O&#39;Neill Groceries Beanie,$29.50,$29.50,$11.80,NaN,2,2,17.70,NaN,1,1
22,$17.95,962834.0,2021-11-10,91-800 - Scarves - Cold weather,CC,C.C&#174; Ribbed Knit Scarf,$29.95,$29.95,$12.00,NaN,186,186,17.95,NaN,1,1
23,$17.95,966791.0,2022-11-02,91-810 - Hats - Cold wthr,CC,C.C&#174; Faux Fur Pom Beanie,$24.95,$24.95,$7.00,NaN,159,159,17.95,NaN,1,1
24,$17.95,966719.0,2022-11-11,91-800 - Scarves - Cold weather,David & Young,David & Young Plaid Fring Scarf,$24.95,$24.95,$7.00,NaN,140,140,17.95,NaN,1,1
25,$17.95,957805.0,2021-10-22,91-810 - Hats - Cold wthr,CC,C.C&#174; Cable Knit Pom Beanie,$24.95,$24.95,$7.00,NaN,1,1,17.95,NaN,1,1
26,$18.45,966718.0,2022-10-10,91-800 - Scarves - Cold weather,David & Young,David & Young Plaid Scarf,$24.95,$24.95,$6.50,NaN,158,158,18.45,NaN,1,1
27,$18.62,966798.0,2022-10-13,91-800 - Scarves - Cold weather,CC,C.C&#174; Classic Ribbed Scarf,$29.95,$29.95,$11.33,NaN,173,173,18.62,NaN,1,1
28,$18.93,966789.0,2022-10-13,91-810 - Hats - Cold wthr,CC,C.C&#174; Pom Beanie,$24.95,$24.95,$6.02,NaN,133,133,18.93,NaN,1,1
29,$21.19,963135.0,2021-12-02,91-810 - Hats - Cold wthr,BKE,BKE Fuzzy Knit Beanie,$24.95,$24.95,$3.76,NaN,109,109,21.19,NaN,1,1
30,$21.95,966797.0,2022-10-13,91-800 - Scarves - Cold weather,CC,C.C&#174; Sequin Ribbed Scarf,$34.95,$34.95,$13.00,NaN,153,153,21.95,NaN,1,1
31,$22.09,957815.0,2022-11-10,91-800 - Scarves - Cold weather,CC,C.C&#174; Boucle Yarn Scarf,$29.95,$29.95,$7.86,NaN,151,151,22.09,NaN,1,1
32,$23.28,967116.0,2022-10-26,91-800 - Scarves - Cold weather,BKE,BKE Blanket Fringe Scarf,$34.95,$34.95,$11.67,NaN,319,319,23.28,NaN,1,1

## WR6
### 91/980
### ALL SKU Margin > 9.95
### OH & OO > 0

In [40]:
# Assign rule to dataframe
WR6 = dict_df.get("WR6.Gals(Reg)91(980)")
print(WR6)

         Margin       SKU Receive Date Last      Class Desc     BRDNM  \
0        $10.00  969262.0        2023-02-10  91-980 - Socks     Lemon
1        $10.00  966478.0        2022-08-05  91-980 - Socks     Lemon
2        $10.00  961950.0        2021-09-16  91-980 - Socks     Lemon
3        $10.05  964521.0        2022-04-18  91-980 - Socks  Muk Luks
4        $10.05  964520.0        2022-03-25  91-980 - Socks  Muk Luks
..          ...       ...               ...             ...       ...
75       $19.79  968119.0        2023-02-14  91-980 - Socks    Stance
76       $19.79  968123.0               NaN  91-980 - Socks    Stance
77       $19.79  969394.0               NaN  91-980 - Socks    Stance
78       $19.79  968122.0               NaN  91-980 - Socks    Stance
79  Grand Total       NaN               NaN             NaN       NaN

                          Product Name Retail Price Sale Price    Cost  \
0   Lemon 3 Pack Air Brush Ankle Socks       $14.00     $14.00   $4.00
1       Lemon 3 Pack Powder Soft Socks       $14.00     $14.00   $4.00
2       Lemon 3 Pack Powder Soft Socks       $14.00     $14.00   $4.00
3          Muk Luks 3 Pack Sport Socks       $14.95     $14.95   $4.90
4          Muk Luks 3 Pack Sport Socks       $14.95     $14.95   $4.90
..                                 ...          ...        ...     ...
75        Stance Absolute 3 Pack Socks       $32.99     $32.99  $13.20
76                                 NaN       $32.99     $32.99  $13.20
77                                 NaN       $32.99     $32.99  $13.20
78                                 NaN       $32.99     $32.99  $13.20
79                                 NaN          NaN        NaN     NaN

    Discount Desc  OH + OO  On Hand Current  Average of Margin $ (LCM)  \
0             NaN      360              120                  10.000000
1             NaN      209               29                  10.000000
2             NaN       22               22                  10.000000
3             NaN      169              169                  10.050000
4             NaN       93               93                  10.050000
..            ...      ...              ...                        ...
75            NaN      161              161                  19.790000
76            NaN      360                0                  19.790000
77            NaN      300                0                  19.790000
78            NaN      360                0                  19.790000
79            NaN    15844            14104                  14.111646

    On Order (PO) All Stores and Dates  SKU6 Count  SKU10 Count
0                                240.0         1.0            1
1                                180.0         1.0            1
2                                  NaN         1.0            1
3                                  NaN         1.0            1
4                                  NaN         1.0            1
..                                 ...         ...          ...
75                                 NaN         1.0            1
76                               360.0         NaN            1
77                               300.0         NaN            1
78                               360.0         NaN            1
79                              1740.0        74.0           80

[80 rows x 16 columns]

In [41]:
WR6_drop_receive_date = WR6.dropna(subset=['Receive Date Last'])
WR6_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$10.00,969262.0,2023-02-10,91-980 - Socks,Lemon,Lemon 3 Pack Air Brush Ankle Socks,$14.00,$14.00,$4.00,NaN,360,120,10.00,240.0,1.0,1
1,$10.00,966478.0,2022-08-05,91-980 - Socks,Lemon,Lemon 3 Pack Powder Soft Socks,$14.00,$14.00,$4.00,NaN,209,29,10.00,180.0,1.0,1
2,$10.00,961950.0,2021-09-16,91-980 - Socks,Lemon,Lemon 3 Pack Powder Soft Socks,$14.00,$14.00,$4.00,NaN,22,22,10.00,NaN,1.0,1
3,$10.05,964521.0,2022-04-18,91-980 - Socks,Muk Luks,Muk Luks 3 Pack Sport Socks,$14.95,$14.95,$4.90,NaN,169,169,10.05,NaN,1.0,1
4,$10.05,964520.0,2022-03-25,91-980 - Socks,Muk Luks,Muk Luks 3 Pack Sport Socks,$14.95,$14.95,$4.90,NaN,93,93,10.05,NaN,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,$18.99,970003.0,2023-01-25,91-980 - Socks,Muk Luks,Muk Luks 3 Pack Slouchy Boot Socks,$24.99,$24.99,$6.00,NaN,164,164,18.99,NaN,1.0,1
72,$19.05,954251.0,2022-04-26,91-980 - Socks,Stance,Stance 3 Pack Sensible Super Invisible Socks,$29.99,$29.99,$10.94,NaN,394,394,19.05,NaN,1.0,2
73,$19.63,954184.0,2022-10-04,91-980 - Socks,Stance,Stance 3 Pack Sensible Super Invisible Socks,$29.99,$29.99,$10.36,NaN,122,122,19.63,NaN,1.0,1
74,$19.79,968120.0,2023-02-14,91-980 - Socks,Stance,Stance Spot On 3 Pack No Show Socks,$32.99,$32.99,$13.20,NaN,195,195,19.79,NaN,1.0,1
75,$19.79,968119.0,2023-02-14,91-980 - Socks,Stance,Stance Absolute 3 Pack Socks,$32.99,$32.99,$13.20,NaN,161,161,19.79,NaN,1.0,1

## WR7 
### 93/100
### ALL SKU with Margin > 16.95
### OH & OO > 0

In [42]:
# Assign rule to dataframe
WR7 = dict_df.get("WR7.Gals(Reg)93(100)")
print(WR7)

         Margin       SKU Receive Date Last         Class Desc    BRDNM  \
0        $24.00  966486.0        2022-11-11  93-100 - Slippers    Lemon
1        $25.95  962390.0        2021-12-01  93-100 - Slippers    Lemon
2        $27.90  965952.0        2022-10-31  93-100 - Slippers    ARIAT
3        $27.90  965948.0        2022-11-28  93-100 - Slippers    ARIAT
4        $31.04  969437.0        2022-11-26  93-100 - Slippers   Very G
5        $31.04  969438.0        2022-11-26  93-100 - Slippers   Very G
6        $31.04  970916.0               NaN  93-100 - Slippers   Very G
7        $31.04  970915.0               NaN  93-100 - Slippers   Very G
8        $33.49  970182.0        2023-02-15  93-100 - Slippers   Very G
9        $36.59  970266.0               NaN  93-100 - Slippers  Bearpaw
10       $36.59  970256.0               NaN  93-100 - Slippers  Bearpaw
11       $38.90  965978.0        2022-11-23  93-100 - Slippers    ARIAT
12       $38.95  966472.0        2022-10-25  93-100 - Slippers  Bearpaw
13       $38.95  966471.0        2022-11-01  93-100 - Slippers  Bearpaw
14       $39.69  970259.0               NaN  93-100 - Slippers  Bearpaw
15       $43.99  970170.0               NaN  93-100 - Slippers  Bearpaw
16       $46.99  970257.0               NaN  93-100 - Slippers  Bearpaw
17       $55.00  969662.0               NaN  93-100 - Slippers    Sorel
18  Grand Total       NaN               NaN                NaN      NaN

                                 Product Name Retail Price Sale Price    Cost  \
0                Lemon Faux Fur Scuff Slipper       $35.00     $35.00  $11.00
1                      Lemon Faux Fur Slipper       $34.95     $34.95   $9.00
2                  Ariat Cozy Leopard Slipper       $49.95     $49.95  $22.05
3                       Ariat Snuggle Slipper       $49.95     $49.95  $22.05
4                   Very G Bruin Mini Slipper       $49.99     $49.99  $18.95
5                   Very G Bruin Mini Slipper       $49.99     $49.99  $18.95
6                                         NaN       $49.99     $49.99  $18.95
7                                         NaN       $49.99     $49.99  $18.95
8                   Very G Bruin Mini Slipper       $49.99     $49.99  $16.50
9                                         NaN       $59.99     $59.99  $23.40
10                                        NaN       $59.99     $59.99  $23.40
11               Ariat Jackie Leather Slipper       $69.95     $69.95  $31.05
12  Bearpaw Loki Exotic Leopard Suede Slipper       $64.95     $64.95  $26.00
13          Bearpaw Loki Exotic Suede Slipper       $64.95     $64.95  $26.00
14                                        NaN       $64.99     $64.99  $25.30
15                                        NaN       $69.99     $69.99  $26.00
16                                        NaN       $74.99     $74.99  $28.00
17                                        NaN      $100.00    $100.00  $45.00
18                                        NaN          NaN        NaN     NaN

    Discount Desc  OH + OO  On Hand Current  Average of Margin $ (LCM)  \
0             NaN        4                4                  24.000000
1             NaN      152              152                  25.950000
2             NaN       29               29                  27.900000
3             NaN        8                8                  27.900000
4             NaN        6                6                  31.040000
5             NaN        2                2                  31.040000
6             NaN      600                0                  31.040000
7             NaN      900                0                  31.040000
8             NaN       93               93                  33.490000
9             NaN      900                0                  36.590000
10            NaN      600                0                  36.590000
11            NaN        2                2                  38.900000
12            NaN       28               28                  38.950000
13            NaN        6                6                  38.950000
14            NaN      300                0                  39.690000
15            NaN     2400                0                  43.990000
16            NaN      600                0                  46.990000
17            NaN      365                0                  55.000000
18            NaN     6995              330                  35.502778

    On Order (PO) All Stores and Dates  SKU6 Count  SKU10 Count
0                                  NaN         1.0            2
1                                  NaN         1.0            3
2                                  NaN         1.0            5
3                                  NaN         1.0            5
4                                  NaN         1.0            4
5                                  NaN         1.0            4
6                                600.0         NaN            6
7                                900.0         NaN            6
8                                  NaN         1.0            6
9                                900.0         NaN            8
10                               600.0         NaN            8
11                                 NaN         1.0            2
12                                 NaN         1.0            7
13                                 NaN         1.0            4
14                               300.0         NaN            8
15                              2400.0         NaN            8
16                               600.0         NaN            8
17                               365.0         NaN            8
18                              6665.0        10.0          102

In [43]:
WR7_drop_receive_date = WR7.dropna(subset=['Receive Date Last'])
WR7_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$24.00,966486.0,2022-11-11,93-100 - Slippers,Lemon,Lemon Faux Fur Scuff Slipper,$35.00,$35.00,$11.00,NaN,4,4,24.00,NaN,1.0,2
1,$25.95,962390.0,2021-12-01,93-100 - Slippers,Lemon,Lemon Faux Fur Slipper,$34.95,$34.95,$9.00,NaN,152,152,25.95,NaN,1.0,3
2,$27.90,965952.0,2022-10-31,93-100 - Slippers,ARIAT,Ariat Cozy Leopard Slipper,$49.95,$49.95,$22.05,NaN,29,29,27.90,NaN,1.0,5
3,$27.90,965948.0,2022-11-28,93-100 - Slippers,ARIAT,Ariat Snuggle Slipper,$49.95,$49.95,$22.05,NaN,8,8,27.90,NaN,1.0,5
4,$31.04,969437.0,2022-11-26,93-100 - Slippers,Very G,Very G Bruin Mini Slipper,$49.99,$49.99,$18.95,NaN,6,6,31.04,NaN,1.0,4
5,$31.04,969438.0,2022-11-26,93-100 - Slippers,Very G,Very G Bruin Mini Slipper,$49.99,$49.99,$18.95,NaN,2,2,31.04,NaN,1.0,4
8,$33.49,970182.0,2023-02-15,93-100 - Slippers,Very G,Very G Bruin Mini Slipper,$49.99,$49.99,$16.50,NaN,93,93,33.49,NaN,1.0,6
11,$38.90,965978.0,2022-11-23,93-100 - Slippers,ARIAT,Ariat Jackie Leather Slipper,$69.95,$69.95,$31.05,NaN,2,2,38.90,NaN,1.0,2
12,$38.95,966472.0,2022-10-25,93-100 - Slippers,Bearpaw,Bearpaw Loki Exotic Leopard Suede Slipper,$64.95,$64.95,$26.00,NaN,28,28,38.95,NaN,1.0,7
13,$38.95,966471.0,2022-11-01,93-100 - Slippers,Bearpaw,Bearpaw Loki Exotic Suede Slipper,$64.95,$64.95,$26.00,NaN,6,6,38.95,NaN,1.0,4

## WR8
### DEPT. 61, 62, 63
### ALL SKU Margin > 17.00
### OH & OO > 0
### 2021 Receipt Year

In [44]:
# Assign rule to dataframe
WR8 = dict_df.get("WR8.Gals61-63(2021)")
print(WR8)

          Margin       SKU Receive Date Last  \
0         $17.03  542721.0        2021-12-18
1         $17.03  542331.0        2021-09-13
2         $17.03  542729.0        2021-12-18
3         $17.03  542730.0        2021-12-22
4         $17.03  541759.0        2021-07-14
..           ...       ...               ...
496       $48.00  541978.0        2021-10-11
497       $48.06  542072.0        2021-11-19
498       $57.02  541874.0        2021-12-09
499       $61.00  541877.0        2021-12-10
500  Grand Total       NaN               NaN

                           Class Desc        BRDNM  \
0     62-130 - S/s Branded Tee shirts     HOWITZER
1     62-130 - S/s Branded Tee shirts     HOWITZER
2     62-130 - S/s Branded Tee shirts     HOWITZER
3     62-130 - S/s Branded Tee shirts     HOWITZER
4     62-130 - S/s Branded Tee shirts     HOWITZER
..                                ...          ...
496   62-605 - 3/4 L/s Casual novelty  FREE PEOPLE
497           62-720 - Fashion Fleece     GIMMICKS
498  62-840 - L/s 3/4 Slv sweatshirts     Wanakome
499  62-840 - L/s 3/4 Slv sweatshirts     Wanakome
500                               NaN          NaN

                              Product Name Retail Price Sale Price    Cost  \
0         Howitzer We Stand United T-Shirt       $26.95     $26.95   $9.92
1          Howitzer Trademark Flag T-Shirt       $26.95     $26.95   $9.92
2         Howitzer Alpha Athletics T-Shirt       $26.95     $26.95   $9.92
3           Howitzer Strong Female T-Shirt       $26.95     $26.95   $9.92
4            Howitzer Liberty Coin T-Shirt       $26.95     $26.95   $9.92
..                                     ...          ...        ...     ...
496         Free People She's A Keeper Top       $88.00     $88.00  $40.00
497         Gimmicks Pieced Crochet Hoodie       $62.95     $62.95  $14.89
498  Wanakome Betty Quarter Zip Sweatshirt       $89.95     $89.95  $32.93
499     Wanakome Artemis Hooded Sweatshirt       $95.00     $95.00  $34.00
500                                    NaN          NaN        NaN     NaN

     Discount Desc  OH + OO  On Hand Current  Average of Margin $ (LCM)  \
0              NaN      111              111                   17.03000
1              NaN       39               39                   17.03000
2              NaN       28               28                   17.03000
3              NaN       27               27                   17.03000
4              NaN        9                9                   17.03000
..             ...      ...              ...                        ...
496            NaN       56               56                   48.00000
497            NaN      242              242                   48.06000
498            NaN       63               63                   57.02000
499            NaN        2                2                   61.00000
500            NaN    41217            41217                   26.23542

     On Order (PO) All Stores and Dates  SKU6 Count  SKU10 Count
0                                   NaN           1            5
1                                   NaN           1            5
2                                   NaN           1            4
3                                   NaN           1            3
4                                   NaN           1            4
..                                  ...         ...          ...
496                                 NaN           1            5
497                                 NaN           1            5
498                                 NaN           1            5
499                                 NaN           1            2
500                                 NaN         500         2101

[501 rows x 16 columns]

In [45]:
WR8_drop_receive_date = WR8.dropna(subset=['Receive Date Last'])
WR8_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$17.03,542721.0,2021-12-18,62-130 - S/s Branded Tee shirts,HOWITZER,Howitzer We Stand United T-Shirt,$26.95,$26.95,$9.92,NaN,111,111,17.03,NaN,1,5
1,$17.03,542331.0,2021-09-13,62-130 - S/s Branded Tee shirts,HOWITZER,Howitzer Trademark Flag T-Shirt,$26.95,$26.95,$9.92,NaN,39,39,17.03,NaN,1,5
2,$17.03,542729.0,2021-12-18,62-130 - S/s Branded Tee shirts,HOWITZER,Howitzer Alpha Athletics T-Shirt,$26.95,$26.95,$9.92,NaN,28,28,17.03,NaN,1,4
3,$17.03,542730.0,2021-12-22,62-130 - S/s Branded Tee shirts,HOWITZER,Howitzer Strong Female T-Shirt,$26.95,$26.95,$9.92,NaN,27,27,17.03,NaN,1,3
4,$17.03,541759.0,2021-07-14,62-130 - S/s Branded Tee shirts,HOWITZER,Howitzer Liberty Coin T-Shirt,$26.95,$26.95,$9.92,NaN,9,9,17.03,NaN,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,$47.45,604480.0,2021-11-05,63-600 - L/s 3/4 Slv hvy wt cardgn,BUCKLE BLACK,Buckle Black Eyelash Knit Cardigan Sweater,$69.95,$69.95,$22.50,NaN,167,167,47.45,NaN,1,5
496,$48.00,541978.0,2021-10-11,62-605 - 3/4 L/s Casual novelty,FREE PEOPLE,Free People She's A Keeper Top,$88.00,$88.00,$40.00,NaN,56,56,48.00,NaN,1,5
497,$48.06,542072.0,2021-11-19,62-720 - Fashion Fleece,GIMMICKS,Gimmicks Pieced Crochet Hoodie,$62.95,$62.95,$14.89,NaN,242,242,48.06,NaN,1,5
498,$57.02,541874.0,2021-12-09,62-840 - L/s 3/4 Slv sweatshirts,Wanakome,Wanakome Betty Quarter Zip Sweatshirt,$89.95,$89.95,$32.93,NaN,63,63,57.02,NaN,1,5
499,$61.00,541877.0,2021-12-10,62-840 - L/s 3/4 Slv sweatshirts,Wanakome,Wanakome Artemis Hooded Sweatshirt,$95.00,$95.00,$34.00,NaN,2,2,61.00,NaN,1,2

## WR9
### 62 - knit tops
### Class 185
### All SKU Margin > 11.00
### Receipt > 10 days
### OH & OO > 0

In [46]:
# Assign rule to dataframe
WR9 = dict_df.get("WR9.Gals62.185")
print(WR9)

         Margin       SKU Receive Date Last            Class Desc     BRDNM  \
0        $11.01  537021.0        2021-01-04  62-185 - Solid Tanks  BKE CORE
1        $11.14  586826.0        2022-10-14  62-185 - Solid Tanks  BKE CORE
2        $11.14  508254.0        2022-12-09  62-185 - Solid Tanks  BKE CORE
3        $11.14  586867.0        2023-02-13  62-185 - Solid Tanks  BKE CORE
4        $11.14  523180.0        2022-04-27  62-185 - Solid Tanks  BKE CORE
..          ...       ...               ...                   ...       ...
59       $12.97  546518.0        2022-12-22  62-185 - Solid Tanks  BKE CORE
60       $12.99  546513.0        2022-12-27  62-185 - Solid Tanks  BKE CORE
61       $13.04  546519.0        2022-12-22  62-185 - Solid Tanks  BKE CORE
62       $13.06  546511.0        2023-03-01  62-185 - Solid Tanks  BKE CORE
63  Grand Total       NaN               NaN                   NaN       NaN

                             Product Name Retail Price Sale Price   Cost  \
0   BKE core Long Length Two Way Tank Top       $15.00     $15.00  $3.99
1     BKE core X-Long Scoop Neck Tank Top       $16.50     $16.50  $5.36
2            BKE core Scoop Neck Tank Top       $16.50     $16.50  $5.36
3     BKE core X-Long Scoop Neck Tank Top       $16.50     $16.50  $5.36
4     BKE core X-Long Scoop Neck Tank Top       $16.50     $16.50  $5.36
..                                    ...          ...        ...    ...
59           BKE core Wide Strap Tank Top       $18.99     $18.99  $6.02
60              BKE core Two Way Tank Top       $18.99     $18.99  $6.00
61           BKE core Wide Strap Tank Top       $18.99     $18.99  $5.95
62       BKE core X-Long Two Way Tank Top       $18.99     $18.99  $5.93
63                                    NaN          NaN        NaN    NaN

    Discount Desc  OH + OO  On Hand Current  Average of Margin $ (LCM)  \
0             NaN        4                4                  11.010000
1             NaN     2991             1191                  11.140000
2             NaN     1176             1176                  11.140000
3             NaN     2779              979                  11.140000
4             NaN      444              444                  11.140000
..            ...      ...              ...                        ...
59            NaN     1410              730                  12.970000
60            NaN      765              765                  12.990000
61            NaN     1565              440                  13.040000
62            NaN     4408             2608                  13.060000
63            NaN    90496            62874                  11.728413

    On Order (PO) All Stores and Dates  SKU6 Count  SKU10 Count
0                                  NaN           1            2
1                               1800.0           1            6
2                                  NaN           1            6
3                               1800.0           1            6
4                                  NaN           1            4
..                                 ...         ...          ...
59                               680.0           1            6
60                                 NaN           1            6
61                              1125.0           1            5
62                              1800.0           1            6
63                             27622.0          63          279

[64 rows x 16 columns]

In [47]:
WR9_drop_receive_date = WR9.dropna(subset=['Receive Date Last'])
WR9_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$11.01,537021.0,2021-01-04,62-185 - Solid Tanks,BKE CORE,BKE core Long Length Two Way Tank Top,$15.00,$15.00,$3.99,NaN,4,4,11.01,NaN,1,2
1,$11.14,586826.0,2022-10-14,62-185 - Solid Tanks,BKE CORE,BKE core X-Long Scoop Neck Tank Top,$16.50,$16.50,$5.36,NaN,2991,1191,11.14,1800.0,1,6
2,$11.14,508254.0,2022-12-09,62-185 - Solid Tanks,BKE CORE,BKE core Scoop Neck Tank Top,$16.50,$16.50,$5.36,NaN,1176,1176,11.14,NaN,1,6
3,$11.14,586867.0,2023-02-13,62-185 - Solid Tanks,BKE CORE,BKE core X-Long Scoop Neck Tank Top,$16.50,$16.50,$5.36,NaN,2779,979,11.14,1800.0,1,6
4,$11.14,523180.0,2022-04-27,62-185 - Solid Tanks,BKE CORE,BKE core X-Long Scoop Neck Tank Top,$16.50,$16.50,$5.36,NaN,444,444,11.14,NaN,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,$11.92,544329.0,2022-06-24,62-185 - Solid Tanks,BKE CORE,BKE core X-Long Two-Way Tank Top,$16.00,$16.00,$4.08,NaN,332,332,11.92,NaN,1,4
59,$12.97,546518.0,2022-12-22,62-185 - Solid Tanks,BKE CORE,BKE core Wide Strap Tank Top,$18.99,$18.99,$6.02,NaN,1410,730,12.97,680.0,1,6
60,$12.99,546513.0,2022-12-27,62-185 - Solid Tanks,BKE CORE,BKE core Two Way Tank Top,$18.99,$18.99,$6.00,NaN,765,765,12.99,NaN,1,6
61,$13.04,546519.0,2022-12-22,62-185 - Solid Tanks,BKE CORE,BKE core Wide Strap Tank Top,$18.99,$18.99,$5.95,NaN,1565,440,13.04,1125.0,1,5
62,$13.06,546511.0,2023-03-01,62-185 - Solid Tanks,BKE CORE,BKE core X-Long Two Way Tank Top,$18.99,$18.99,$5.93,NaN,4408,2608,13.06,1800.0,1,6

## WR10
### 62 - Knit tops
### Class 130
### ALL SKU Margin > 14.00
### Receipt > 10 days
### OH & OO > 0

In [48]:
# Assign rule to dataframe
WR10 = dict_df.get("WR10.Gals62.130>14.00")
print(WR10)

          Margin       SKU Receive Date Last                       Class Desc  \
0         $14.12  544501.0        2022-02-04  62-130 - S/s Branded Tee shirts
1         $14.12  544499.0        2022-02-16  62-130 - S/s Branded Tee shirts
2         $14.12  543019.0        2022-08-10  62-130 - S/s Branded Tee shirts
3         $14.40  545835.0        2023-03-03  62-130 - S/s Branded Tee shirts
4         $14.40  545826.0        2023-02-08  62-130 - S/s Branded Tee shirts
..           ...       ...               ...                              ...
674       $42.50  543644.0        2022-01-17  62-130 - S/s Branded Tee shirts
675       $42.50  542427.0        2021-12-17  62-130 - S/s Branded Tee shirts
676       $42.50  545144.0        2022-08-03  62-130 - S/s Branded Tee shirts
677       $45.50  546304.0        2023-02-06  62-130 - S/s Branded Tee shirts
678  Grand Total       NaN               NaN                              NaN

          BRDNM                        Product Name Retail Price Sale Price  \
0         ARIAT             Ariat Real Logo T-Shirt       $26.95     $26.95
1         ARIAT      Ariat Real Logo Script T-Shirt       $26.95     $26.95
2         ARIAT       Ariat Not In The Mood T-Shirt       $26.95     $26.95
3     Salt Life          Salt Life Palmline T-Shirt       $24.00     $24.00
4     Salt Life  Salt Life Sea Escape Badge T-Shirt       $24.00     $24.00
..          ...                                 ...          ...        ...
674  AFFLICTION            Affliction Vieja T-Shirt       $68.00     $68.00
675  AFFLICTION      Affliction Hyper Speed T-Shirt       $68.00     $68.00
676  AFFLICTION    Affliction Cryptic Venom T-Shirt       $68.00     $68.00
677  AFFLICTION       Affliction Twin Tribe T-Shirt       $68.00     $68.00
678         NaN                                 NaN          NaN        NaN

       Cost  Discount Desc  OH + OO  On Hand Current  \
0    $12.83            NaN        6                6
1    $12.83            NaN        6                6
2    $12.83            NaN        2                2
3     $9.60            NaN      715              715
4     $9.60            NaN      258              258
..      ...            ...      ...              ...
674  $25.50            NaN       55               55
675  $25.50            NaN       41               41
676  $25.50            NaN       16               16
677  $22.50            NaN      276              276
678     NaN            NaN   243440            86135

     Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  \
0                    14.120000                                 NaN
1                    14.120000                                 NaN
2                    14.120000                                 NaN
3                    14.400000                                 NaN
4                    14.400000                                 NaN
..                         ...                                 ...
674                  42.500000                                 NaN
675                  42.500000                                 NaN
676                  42.500000                                 NaN
677                  45.500000                                 NaN
678                  23.284277                            157305.0

     SKU6 Count  SKU10 Count
0           1.0            3
1           1.0            2
2           1.0            2
3           1.0            4
4           1.0            4
..          ...          ...
674         1.0            6
675         1.0            6
676         1.0            3
677         1.0            5
678       513.0         3059

[679 rows x 16 columns]

In [49]:
WR10_drop_receive_date = WR10.dropna(subset=['Receive Date Last'])
WR10_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$14.12,544501.0,2022-02-04,62-130 - S/s Branded Tee shirts,ARIAT,Ariat Real Logo T-Shirt,$26.95,$26.95,$12.83,NaN,6,6,14.12,NaN,1.0,3
1,$14.12,544499.0,2022-02-16,62-130 - S/s Branded Tee shirts,ARIAT,Ariat Real Logo Script T-Shirt,$26.95,$26.95,$12.83,NaN,6,6,14.12,NaN,1.0,2
2,$14.12,543019.0,2022-08-10,62-130 - S/s Branded Tee shirts,ARIAT,Ariat Not In The Mood T-Shirt,$26.95,$26.95,$12.83,NaN,2,2,14.12,NaN,1.0,2
3,$14.40,545835.0,2023-03-03,62-130 - S/s Branded Tee shirts,Salt Life,Salt Life Palmline T-Shirt,$24.00,$24.00,$9.60,NaN,715,715,14.40,NaN,1.0,4
4,$14.40,545826.0,2023-02-08,62-130 - S/s Branded Tee shirts,Salt Life,Salt Life Sea Escape Badge T-Shirt,$24.00,$24.00,$9.60,NaN,258,258,14.40,NaN,1.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,$42.50,543995.0,2022-04-13,62-130 - S/s Branded Tee shirts,AFFLICTION,Affliction Scared Oath T-Shirt,$68.00,$68.00,$25.50,NaN,83,83,42.50,NaN,1.0,3
674,$42.50,543644.0,2022-01-17,62-130 - S/s Branded Tee shirts,AFFLICTION,Affliction Vieja T-Shirt,$68.00,$68.00,$25.50,NaN,55,55,42.50,NaN,1.0,6
675,$42.50,542427.0,2021-12-17,62-130 - S/s Branded Tee shirts,AFFLICTION,Affliction Hyper Speed T-Shirt,$68.00,$68.00,$25.50,NaN,41,41,42.50,NaN,1.0,6
676,$42.50,545144.0,2022-08-03,62-130 - S/s Branded Tee shirts,AFFLICTION,Affliction Cryptic Venom T-Shirt,$68.00,$68.00,$25.50,NaN,16,16,42.50,NaN,1.0,3
677,$45.50,546304.0,2023-02-06,62-130 - S/s Branded Tee shirts,AFFLICTION,Affliction Twin Tribe T-Shirt,$68.00,$68.00,$22.50,NaN,276,276,45.50,NaN,1.0,5

## WR11A
### ALL SKU w Margin > 18.50 and OH & OO > 0
### DC 61 & 62 wth receipt > 10 days

In [50]:
# Assign rule to dataframe
WR11A = dict_df.get("WR11a.Gals61&62>$18.5")
print(WR11A)

           Margin       SKU Receive Date Last  \
0          $18.53  543441.0        2022-06-08
1          $18.54  546575.0        2023-01-26
2          $18.54  546541.0        2023-01-05
3          $18.55  545511.0        2022-07-27
4          $18.55  542829.0        2022-02-18
...           ...       ...               ...
4065       $81.69  545608.0        2022-09-28
4066       $90.00  548301.0               NaN
4067       $90.00  548291.0               NaN
4068       $92.00  545987.0        2022-11-16
4069  Grand Total       NaN               NaN

                              Class Desc         BRDNM  \
0       62-172 - Sleeveless Screen Print        Hurley
1      62-140 - S/s Non Branded t shirts   FITZ + EDDI
2                     62-178 - Bralettes  BKEssentials
3        62-130 - S/s Branded Tee shirts         ARIAT
4                     62-178 - Bralettes  BKEssentials
...                                  ...           ...
4065  61-720 - 3/4 Ls Slv synthc bt frnt   FREE PEOPLE
4066   62-460 - Sleeved Knit Bttn fronts      Z Supply
4067   62-460 - Sleeved Knit Bttn fronts      Z Supply
4068          62-620 - L/s Fashion Knits   FREE PEOPLE
4069                                 NaN           NaN

                                         Product Name Retail Price Sale Price  \
0                        Hurley Hallie Beach Tank Top       $29.00     $29.00
1        FITZ &#43; EDDI Sunflower T-Shirt - One Size       $24.99     $24.99
2     BKEssentials Floral Lace Full Coverage Bralette       $26.99     $26.99
3                                 Ariat Peace T-Shirt       $29.95     $29.95
4                      BKEssentials Ribbed Knit Brami       $22.95     $22.95
...                                               ...          ...        ...
4065                Free People My Best Velvet Blouse      $148.00    $148.00
4066                                              NaN      $129.00    $129.00
4067                                              NaN      $129.00    $129.00
4068         Free People Pixie Crinkle Tunic Pullover      $168.00    $168.00
4069                                              NaN          NaN        NaN

        Cost  Discount Desc  OH + OO  On Hand Current  \
0     $10.47            NaN        7                7
1      $6.45            NaN      779              779
2      $8.45            NaN     3750              750
3     $11.40            NaN      117              117
4      $4.40            NaN       96               96
...      ...            ...      ...              ...
4065  $66.31            NaN       16               16
4066  $39.00            NaN      480                0
4067  $39.00            NaN      600                0
4068  $76.00            NaN        8                8
4069     NaN            NaN  2463663           814201

      Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  \
0                     18.530000                                 NaN
1                     18.540000                                 NaN
2                     18.540000                              3000.0
3                     18.550000                                 NaN
4                     18.550000                                 NaN
...                         ...                                 ...
4065                  81.690000                                 NaN
4066                  90.000000                               480.0
4067                  90.000000                               600.0
4068                  92.000000                                 NaN
4069                  28.547658                           1649462.0

      SKU6 Count  SKU10 Count
0            1.0            4
1            1.0            1
2            1.0            5
3            1.0            5
4            1.0            2
...          ...          ...
4065         1.0            5
4066         NaN            5
4067         NaN            6
4068         1.0            4
4069      2962.0        19225

[4070 rows x 16 columns]

In [51]:
WR11A_drop_receive_date = WR11A.dropna(subset=['Receive Date Last'])
WR11A_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$18.53,543441.0,2022-06-08,62-172 - Sleeveless Screen Print,Hurley,Hurley Hallie Beach Tank Top,$29.00,$29.00,$10.47,NaN,7,7,18.53,NaN,1.0,4
1,$18.54,546575.0,2023-01-26,62-140 - S/s Non Branded t shirts,FITZ + EDDI,FITZ &#43; EDDI Sunflower T-Shirt - One Size,$24.99,$24.99,$6.45,NaN,779,779,18.54,NaN,1.0,1
2,$18.54,546541.0,2023-01-05,62-178 - Bralettes,BKEssentials,BKEssentials Floral Lace Full Coverage Bralette,$26.99,$26.99,$8.45,NaN,3750,750,18.54,3000.0,1.0,5
3,$18.55,545511.0,2022-07-27,62-130 - S/s Branded Tee shirts,ARIAT,Ariat Peace T-Shirt,$29.95,$29.95,$11.40,NaN,117,117,18.55,NaN,1.0,5
4,$18.55,542829.0,2022-02-18,62-178 - Bralettes,BKEssentials,BKEssentials Ribbed Knit Brami,$22.95,$22.95,$4.40,NaN,96,96,18.55,NaN,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4056,$70.40,544964.0,2022-09-21,62-840 - L/s 3/4 Slv sweatshirts,Wanakome,Wanakome Becky Quarter Zip Pullover,$110.00,$110.00,$39.60,NaN,1,1,70.40,NaN,1.0,1
4058,$72.55,543438.0,2022-02-18,62-840 - L/s 3/4 Slv sweatshirts,Wanakome,Wanakome Shelina Lace-Up Hooded Sweatshirt,$114.95,$114.95,$42.40,NaN,9,9,72.55,NaN,1.0,4
4064,$81.00,545607.0,2022-09-27,61-720 - 3/4 Ls Slv synthc bt frnt,FREE PEOPLE,Free People My Best Velvet Blouse,$148.00,$148.00,$67.00,NaN,17,17,81.00,NaN,1.0,5
4065,$81.69,545608.0,2022-09-28,61-720 - 3/4 Ls Slv synthc bt frnt,FREE PEOPLE,Free People My Best Velvet Blouse,$148.00,$148.00,$66.31,NaN,16,16,81.69,NaN,1.0,5
4068,$92.00,545987.0,2022-11-16,62-620 - L/s Fashion Knits,FREE PEOPLE,Free People Pixie Crinkle Tunic Pullover,$168.00,$168.00,$76.00,NaN,8,8,92.00,NaN,1.0,4

## WR11B
### ALL SKU Margin > 18.50 and OH & OO > 0
### DC 63 & 76
### no receipt exclusion

In [52]:
# Assign rule to dataframe
WR11B = dict_df.get("WR11b.Gals63&76>$18.5")
print(WR11B)

           Margin       SKU Receive Date Last  \
0          $19.21  309531.0        2021-05-06
1          $19.25  310247.0        2022-04-14
2          $19.25  309047.0        2021-04-20
3          $19.25  309048.0        2021-04-20
4          $19.27  604554.0        2021-12-06
...           ...       ...               ...
1233       $91.74  308931.0        2020-07-07
1234       $91.74  308607.0        2021-02-08
1235       $92.00  604908.0        2022-07-21
1236       $94.40  310822.0        2022-06-24
1237  Grand Total       NaN               NaN

                              Class Desc          BRDNM  \
0                 76-640 - Lounge Shorts  GILDED INTENT
1             76-710 - Active Bras/tanks       Champion
2             76-710 - Active Bras/tanks       Champion
3             76-710 - Active Bras/tanks       Champion
4       63-720 - 3/4 L/s Pullover hvy wt        DAYTRIP
...                                  ...            ...
1233               76-440 - Denim Shorts   Rock Revival
1234               76-440 - Denim Shorts   Rock Revival
1235  63-600 - L/s 3/4 Slv hvy wt cardgn    FREE PEOPLE
1236               76-440 - Denim Shorts   Rock Revival
1237                                 NaN            NaN

                                           Product Name Retail Price  \
0                 Gilded Intent Distressed Lounge Short       $24.95
1         Champion&#174; Everyday Asymmetrical Tank Top       $35.00
2     Champion&#174; Eco Sculpt Active Cropped Tank Top       $35.00
3     Champion&#174; Eco Sculpt Active Cropped Tank Top       $35.00
4                    Daytrip Pointelle Chenille Sweater       $42.95
...                                                 ...          ...
1233  Rock Revival Barbra Mid-Rise Stretch Cuffed Short      $139.00
1234        Rock Revival Katydid Mid-Rise Stretch Short      $139.00
1235                 Free People Sepia Cardigan Sweater      $168.00
1236            Rock Revival Dao Mid-Rise Stretch Short      $144.00
1237                                                NaN          NaN

     Sale Price    Cost  Discount Desc  OH + OO  On Hand Current  \
0        $24.95   $5.74            NaN       61               61
1        $35.00  $15.75            NaN       58               58
2        $35.00  $15.75            NaN        8                8
3        $35.00  $15.75            NaN        4                4
4        $42.95  $23.68            NaN        2                2
...         ...     ...            ...      ...              ...
1233    $139.00  $47.26            NaN        2                2
1234    $139.00  $47.26            NaN        2                2
1235    $168.00  $76.00            NaN       19               19
1236    $144.00  $49.60            NaN       26               26
1237        NaN     NaN            NaN   685190           257069

      Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  \
0                     19.210000                                 NaN
1                     19.250000                                 NaN
2                     19.250000                                 NaN
3                     19.250000                                 NaN
4                     19.270000                                 NaN
...                         ...                                 ...
1233                  91.740000                                 NaN
1234                  91.740000                                 NaN
1235                  92.000000                                 NaN
1236                  94.400000                                 NaN
1237                  37.727437                            428121.0

      SKU6 Count  SKU10 Count
0            1.0            5
1            1.0            4
2            1.0            4
3            1.0            3
4            1.0            1
...          ...          ...
1233         1.0            2
1234         1.0            2
1235         1.0            4
1236         1.0           10
1237       963.0         7160

[1238 rows x 16 columns]

In [53]:
WR11B_drop_receive_date = WR11B.dropna(subset=['Receive Date Last'])
WR11B_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$19.21,309531.0,2021-05-06,76-640 - Lounge Shorts,GILDED INTENT,Gilded Intent Distressed Lounge Short,$24.95,$24.95,$5.74,NaN,61,61,19.21,NaN,1.0,5
1,$19.25,310247.0,2022-04-14,76-710 - Active Bras/tanks,Champion,Champion&#174; Everyday Asymmetrical Tank Top,$35.00,$35.00,$15.75,NaN,58,58,19.25,NaN,1.0,4
2,$19.25,309047.0,2021-04-20,76-710 - Active Bras/tanks,Champion,Champion&#174; Eco Sculpt Active Cropped Tank Top,$35.00,$35.00,$15.75,NaN,8,8,19.25,NaN,1.0,4
3,$19.25,309048.0,2021-04-20,76-710 - Active Bras/tanks,Champion,Champion&#174; Eco Sculpt Active Cropped Tank Top,$35.00,$35.00,$15.75,NaN,4,4,19.25,NaN,1.0,3
4,$19.27,604554.0,2021-12-06,63-720 - 3/4 L/s Pullover hvy wt,DAYTRIP,Daytrip Pointelle Chenille Sweater,$42.95,$42.95,$23.68,NaN,2,2,19.27,NaN,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1232,$91.74,308448.0,2020-06-18,76-440 - Denim Shorts,Rock Revival,Rock Revival Sepia Easy Stretch Short,$139.00,$139.00,$47.26,NaN,2,2,91.74,NaN,1.0,2
1233,$91.74,308931.0,2020-07-07,76-440 - Denim Shorts,Rock Revival,Rock Revival Barbra Mid-Rise Stretch Cuffed Short,$139.00,$139.00,$47.26,NaN,2,2,91.74,NaN,1.0,2
1234,$91.74,308607.0,2021-02-08,76-440 - Denim Shorts,Rock Revival,Rock Revival Katydid Mid-Rise Stretch Short,$139.00,$139.00,$47.26,NaN,2,2,91.74,NaN,1.0,2
1235,$92.00,604908.0,2022-07-21,63-600 - L/s 3/4 Slv hvy wt cardgn,FREE PEOPLE,Free People Sepia Cardigan Sweater,$168.00,$168.00,$76.00,NaN,19,19,92.00,NaN,1.0,4
1236,$94.40,310822.0,2022-06-24,76-440 - Denim Shorts,Rock Revival,Rock Revival Dao Mid-Rise Stretch Short,$144.00,$144.00,$49.60,NaN,26,26,94.40,NaN,1.0,10

## WR12 
### 91/820
### ALL SKU Margin > 16.99 and OH & OO > 0

In [54]:
# Assign rule to dataframe
WR12 = dict_df.get("WR12.Gals91.820(Reg)")
print(WR12)

          Margin       SKU Receive Date Last             Class Desc  \
0         $17.20  965642.0        2022-07-08  91-820 - Fashion Hats
1         $17.20  965557.0        2022-04-29  91-820 - Fashion Hats
2         $17.45  965931.0        2022-06-07  91-820 - Fashion Hats
3         $17.70  965932.0        2022-06-13  91-820 - Fashion Hats
4         $18.86  961769.0        2021-08-19  91-820 - Fashion Hats
..           ...       ...               ...                    ...
204       $19.79  970802.0               NaN  91-820 - Fashion Hats
205       $21.24  970827.0               NaN  91-820 - Fashion Hats
206       $22.26  970847.0               NaN  91-820 - Fashion Hats
207       $22.26  970845.0               NaN  91-820 - Fashion Hats
208  Grand Total       NaN               NaN                    NaN

                    BRDNM                               Product Name  \
0                      CC        C.C&#174; Camo Ripstop Baseball Hat
1                      CC  C.C&#174; Cow Print Ponytail Baseball Hat
2                WRANGLER   Wrangler&#174; x Yellowstone Trucker Hat
3                WRANGLER  Wrangler&#174; x Yellowstone Baseball Hat
4             H3 Headwear     H3 Headwear Yosemite National Park Hat
..                    ...                                        ...
204         David & Young                                        NaN
205  Original Retro Brand                                        NaN
206                 Hooey                                        NaN
207                 Hooey                                        NaN
208                   NaN                                        NaN

    Retail Price Sale Price    Cost  Discount Desc  OH + OO  On Hand Current  \
0         $24.95     $24.95   $7.75            NaN       22               22
1         $24.95     $24.95   $7.75            NaN        1                1
2         $24.95     $24.95   $7.50            NaN        1                1
3         $24.95     $24.95   $7.25            NaN       11               11
4         $24.95     $24.95   $6.09            NaN        1                1
..           ...        ...     ...            ...      ...              ...
204       $24.99     $24.99   $5.20            NaN      900                0
205       $29.99     $29.99   $8.75            NaN     1200                0
206       $36.99     $36.99  $14.73            NaN      180                0
207       $36.99     $36.99  $14.73            NaN      360                0
208          NaN        NaN     NaN            NaN    69679            26424

     Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  \
0                     17.20000                                 NaN
1                     17.20000                                 NaN
2                     17.45000                                 NaN
3                     17.70000                                 NaN
4                     18.86000                                 NaN
..                         ...                                 ...
204                   19.79000                               900.0
205                   21.24000                              1200.0
206                   22.26000                               180.0
207                   22.26000                               360.0
208                   28.61024                             43255.0

     SKU6 Count  SKU10 Count
0           1.0            1
1           1.0            1
2           1.0            1
3           1.0            1
4           1.0            1
..          ...          ...
204         NaN            1
205         NaN            1
206         NaN            1
207         NaN            1
208       151.0          218

[209 rows x 16 columns]

In [55]:
WR12_drop_receive_date = WR12.dropna(subset=['Receive Date Last'])
WR12_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$17.20,965642.0,2022-07-08,91-820 - Fashion Hats,CC,C.C&#174; Camo Ripstop Baseball Hat,$24.95,$24.95,$7.75,NaN,22,22,17.20,NaN,1.0,1
1,$17.20,965557.0,2022-04-29,91-820 - Fashion Hats,CC,C.C&#174; Cow Print Ponytail Baseball Hat,$24.95,$24.95,$7.75,NaN,1,1,17.20,NaN,1.0,1
2,$17.45,965931.0,2022-06-07,91-820 - Fashion Hats,WRANGLER,Wrangler&#174; x Yellowstone Trucker Hat,$24.95,$24.95,$7.50,NaN,1,1,17.45,NaN,1.0,1
3,$17.70,965932.0,2022-06-13,91-820 - Fashion Hats,WRANGLER,Wrangler&#174; x Yellowstone Baseball Hat,$24.95,$24.95,$7.25,NaN,11,11,17.70,NaN,1.0,1
4,$18.86,961769.0,2021-08-19,91-820 - Fashion Hats,H3 Headwear,H3 Headwear Yosemite National Park Hat,$24.95,$24.95,$6.09,NaN,1,1,18.86,NaN,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,$17.44,969225.0,2022-11-23,91-820 - Fashion Hats,Worn West,Worn/West Dolly Corduroy Baseball Hat,$24.99,$24.99,$7.55,NaN,43,43,17.44,NaN,1.0,1
197,$19.90,967240.0,2023-01-16,91-820 - Fashion Hats,BILLABONG,Billabong Tipton Lifeguard Hat,$32.95,$32.95,$13.05,NaN,94,94,19.90,NaN,1.0,1
198,$30.00,967552.0,2023-01-25,91-820 - Fashion Hats,GOORIN ACCESSORIES,Goorin Bros. Smile More Trucker Hat,$50.00,$50.00,$20.00,NaN,74,74,30.00,NaN,1.0,1
199,$26.49,961547.0,2023-03-01,91-820 - Fashion Hats,Kimes Ranch,Kimes Ranch Boneyard Trucker Hat,$39.99,$39.99,$13.50,NaN,507,507,26.49,NaN,1.0,1
200,$21.33,966396.0,2023-03-21,91-820 - Fashion Hats,Hooey,Hooey John Wayne Cattle Co. Trucker Hat,$36.99,$36.99,$15.66,NaN,745,745,21.33,NaN,1.0,1

## WR13
### 93/600&650
### ALL SKU Margin > 17.99 and OH & OO > 0

In [56]:
# Assign rule to dataframe
WR13 = dict_df.get("WR13.Gals93.600&650(Reg)")
print(WR13)

          Margin       SKU Receive Date Last               Class Desc  \
0         $17.01  964070.0        2022-06-01  93-600 - Active Sandals
1         $17.62  953108.0        2022-01-17  93-600 - Active Sandals
2         $18.09  969619.0               NaN  93-600 - Active Sandals
3         $18.10  963603.0        2022-02-14  93-600 - Active Sandals
4         $18.55  964200.0        2022-05-27  93-600 - Active Sandals
..           ...       ...               ...                      ...
247       $86.38  969904.0               NaN    93-650 - Flat Sandals
248       $91.12  956872.0        2022-10-05    93-650 - Flat Sandals
249       $95.00  964047.0        2022-03-31    93-650 - Flat Sandals
250       $96.87  965624.0        2022-08-21    93-650 - Flat Sandals
251  Grand Total       NaN               NaN                      NaN

                      BRDNM                               Product Name  \
0                       MIA                             Mia Lexa Slide
1                      Reef                 Reef Stargazer Bounce Flip
2    Sunshineo Imp & Exp Co                                        NaN
3                    Cobian                  Cobian Fiesta Bounce Flip
4                   Bossion         Adventure Tonal Embroidered Sandal
..                      ...                                        ...
247             Birkenstock                                        NaN
248             Birkenstock   Birkenstock&#174; Arizona Leather Sandal
249                 Bed Stu              Bed Stu Candie Leather Sandal
250             Birkenstock  Birkenstock&#174; Papillio Arizona Sandal
251                     NaN                                        NaN

    Retail Price Sale Price    Cost  Discount Desc  OH + OO  On Hand Current  \
0         $24.95     $24.95   $7.94            NaN      122              122
1         $32.00     $32.00  $14.38            NaN       26               26
2         $24.99     $24.99   $6.90            NaN     1500                0
3         $32.95     $32.95  $14.85            NaN      144              144
4         $26.95     $26.95   $8.40            NaN     1494             1494
..           ...        ...     ...            ...      ...              ...
247      $160.00    $160.00  $73.62            NaN       60                0
248      $160.00    $160.00  $68.88            NaN        2                2
249      $175.00    $175.00  $80.00            NaN       98               98
250      $180.00    $180.00  $83.13            NaN       17               17
251          NaN        NaN     NaN            NaN   104093            51182

     Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  \
0                    17.010000                                 NaN
1                    17.620000                                 NaN
2                    18.090000                              1500.0
3                    18.100000                                 NaN
4                    18.550000                                 NaN
..                         ...                                 ...
247                  86.380000                                60.0
248                  91.120000                                 NaN
249                  95.000000                                 NaN
250                  96.870000                                 NaN
251                  43.976215                             52911.0

     SKU6 Count  SKU10 Count
0           1.0            7
1           1.0            5
2           NaN            5
3           1.0            7
4           1.0            7
..          ...          ...
247         NaN            6
248         1.0            2
249         1.0           10
250         1.0            7
251       191.0         1695

[252 rows x 16 columns]

In [57]:
WR13_drop_receive_date = WR13.dropna(subset=['Receive Date Last'])
WR13_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$17.01,964070.0,2022-06-01,93-600 - Active Sandals,MIA,Mia Lexa Slide,$24.95,$24.95,$7.94,NaN,122,122,17.01,NaN,1.0,7
1,$17.62,953108.0,2022-01-17,93-600 - Active Sandals,Reef,Reef Stargazer Bounce Flip,$32.00,$32.00,$14.38,NaN,26,26,17.62,NaN,1.0,5
3,$18.10,963603.0,2022-02-14,93-600 - Active Sandals,Cobian,Cobian Fiesta Bounce Flip,$32.95,$32.95,$14.85,NaN,144,144,18.10,NaN,1.0,7
4,$18.55,964200.0,2022-05-27,93-600 - Active Sandals,Bossion,Adventure Tonal Embroidered Sandal,$26.95,$26.95,$8.40,NaN,1494,1494,18.55,NaN,1.0,7
5,$18.57,958868.0,2021-05-27,93-600 - Active Sandals,Cobian,Cobian&#174; Soleil&#8482; Flip,$29.95,$29.95,$11.38,NaN,68,68,18.57,NaN,1.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,$85.90,965626.0,2022-10-05,93-650 - Flat Sandals,Birkenstock,Birkenstock&#174; Arizona Suede Shearling Sandal,$160.00,$160.00,$74.10,NaN,1,1,85.90,NaN,1.0,1
246,$86.37,965625.0,2023-02-13,93-650 - Flat Sandals,Birkenstock,Birkenstock&#174; Arizona Oiled Leather Sandal,$160.00,$160.00,$73.63,NaN,167,167,86.37,NaN,1.0,7
248,$91.12,956872.0,2022-10-05,93-650 - Flat Sandals,Birkenstock,Birkenstock&#174; Arizona Leather Sandal,$160.00,$160.00,$68.88,NaN,2,2,91.12,NaN,1.0,2
249,$95.00,964047.0,2022-03-31,93-650 - Flat Sandals,Bed Stu,Bed Stu Candie Leather Sandal,$175.00,$175.00,$80.00,NaN,98,98,95.00,NaN,1.0,10
250,$96.87,965624.0,2022-08-21,93-650 - Flat Sandals,Birkenstock,Birkenstock&#174; Papillio Arizona Sandal,$180.00,$180.00,$83.13,NaN,17,17,96.87,NaN,1.0,7

## WR14
### 96 : Margin > 15.00 and OH & OO > 0

In [58]:
# Assign rule to dataframe
WR14 = dict_df.get("WR14.Gals96")
print(WR14)

           Margin       SKU Receive Date Last                    Class Desc  \
0          $15.08  542290.0        2022-03-18             96-590 - S/s Tees
1          $15.17  542292.0        2022-03-15             96-590 - S/s Tees
2          $15.40  203809.0        2022-10-21  96-230 - Knit Active Bottoms
3          $15.40  966689.0        2022-10-20             96-910 - Slippers
4          $15.40  204097.0               NaN  96-230 - Knit Active Bottoms
...           ...       ...               ...                           ...
1064       $52.80  161411.0               NaN          96-100 - Denim Jeans
1065       $56.00  160578.0               NaN          96-100 - Denim Jeans
1066       $57.75  965478.0        2022-11-07                96-900 - Boots
1067       $57.75  969690.0               NaN                96-900 - Boots
1068  Grand Total       NaN               NaN                           NaN

             BRDNM                                   Product Name  \
0            ARIAT             Girls - Ariat Real Kinship T-Shirt
1            ARIAT          Girls - Ariat Real Yuma Print T-Shirt
2     Little Lemon   Girls - Little Lemon Faux Fur Lined Leggings
3     Little Lemon  Girls - Little Lemon Apres Ski Bootie Slipper
4     Little Lemon                                            NaN
...            ...                                            ...
1064       MISS ME                                            NaN
1065       MISS ME                                            NaN
1066         Sorel     Girls - Sorel Explorer&#8482; Leather Boot
1067         Sorel                                            NaN
1068           NaN                                            NaN

     Retail Price Sale Price    Cost  Discount Desc  OH + OO  On Hand Current  \
0          $26.95     $26.95  $11.87            NaN        6                6
1          $28.95     $28.95  $13.78            NaN       10               10
2          $22.00     $22.00   $6.60            NaN      135                9
3          $22.00     $22.00   $6.60            NaN        4                4
4          $22.00     $22.00   $6.60            NaN       54                0
...           ...        ...     ...            ...      ...              ...
1064       $88.00     $88.00  $35.20            NaN      520                0
1065       $84.00     $84.00  $28.00            NaN      535                0
1066      $105.00    $105.00  $47.25            NaN       64               64
1067      $105.00    $105.00  $47.25            NaN       60                0
1068          NaN        NaN     NaN            NaN   462299           123262

      Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  \
0                     15.080000                                 NaN
1                     15.170000                                 NaN
2                     15.400000                               126.0
3                     15.400000                                 NaN
4                     15.400000                                54.0
...                         ...                                 ...
1064                  52.800000                               520.0
1065                  56.000000                               535.0
1066                  57.750000                                 NaN
1067                  57.750000                                60.0
1068                  25.686311                            339037.0

      SKU6 Count  SKU10 Count
0            1.0            3
1            1.0            4
2            1.0            3
3            1.0            2
4            NaN            3
...          ...          ...
1064         NaN            8
1065         NaN            8
1066         1.0            5
1067         NaN            5
1068       725.0         5491

[1069 rows x 16 columns]

In [59]:
WR14_drop_receive_date = WR14.dropna(subset=['Receive Date Last'])
WR14_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$15.08,542290.0,2022-03-18,96-590 - S/s Tees,ARIAT,Girls - Ariat Real Kinship T-Shirt,$26.95,$26.95,$11.87,NaN,6,6,15.08,NaN,1.0,3
1,$15.17,542292.0,2022-03-15,96-590 - S/s Tees,ARIAT,Girls - Ariat Real Yuma Print T-Shirt,$28.95,$28.95,$13.78,NaN,10,10,15.17,NaN,1.0,4
2,$15.40,203809.0,2022-10-21,96-230 - Knit Active Bottoms,Little Lemon,Girls - Little Lemon Faux Fur Lined Leggings,$22.00,$22.00,$6.60,NaN,135,9,15.40,126.0,1.0,3
3,$15.40,966689.0,2022-10-20,96-910 - Slippers,Little Lemon,Girls - Little Lemon Apres Ski Bootie Slipper,$22.00,$22.00,$6.60,NaN,4,4,15.40,NaN,1.0,2
5,$15.45,544231.0,2022-04-21,96-590 - S/s Tees,Goodie Two Sleeves Kids,Girls - Goodie Two Sleeves Mini T-Shirt,$22.95,$22.95,$7.50,NaN,130,130,15.45,NaN,1.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049,$52.80,159726.0,2023-03-10,96-100 - Denim Jeans,MISS ME,Girls - Miss Me Mid-Rise Boot Stretch Jean,$88.00,$88.00,$35.20,NaN,253,253,52.80,NaN,1.0,8
1050,$52.80,160614.0,2023-03-20,96-100 - Denim Jeans,MISS ME,Girls - Miss Me Mid-Rise Boot Stretch Jean,$88.00,$88.00,$35.20,NaN,223,223,52.80,NaN,1.0,6
1051,$52.80,161102.0,2023-02-20,96-100 - Denim Jeans,MISS ME,Girls - Miss Me Mid-Rise Flare Stretch Jean,$88.00,$88.00,$35.20,NaN,76,76,52.80,NaN,1.0,5
1052,$52.80,161101.0,2023-02-10,96-100 - Denim Jeans,MISS ME,Girls - Miss Me Mid-Rise Flare Stretch Jean,$88.00,$88.00,$35.20,NaN,60,60,52.80,NaN,1.0,5
1066,$57.75,965478.0,2022-11-07,96-900 - Boots,Sorel,Girls - Sorel Explorer&#8482; Leather Boot,$105.00,$105.00,$47.25,NaN,64,64,57.75,NaN,1.0,5

## WR15
### include 542325, 542326, 542323, 545424

In [60]:
# Assign rule to dataframe
WR15 = dict_df.get("WR.15GalsSKU")
print(WR15)

        Margin       SKU Receive Date Last                       Class Desc  \
0       $18.00  542325.0        2022-04-08  62-130 - S/s Branded Tee shirts
1       $18.00  542326.0        2022-04-08  62-130 - S/s Branded Tee shirts
2       $18.00  545424.0        2022-05-04  62-130 - S/s Branded Tee shirts
3       $18.00  542323.0        2022-05-04  62-130 - S/s Branded Tee shirts
4  Grand Total       NaN               NaN                              NaN

      BRDNM                                    Product Name Retail Price  \
0  WRANGLER    Wrangler&#174; x Fender&#174; Ringer T-Shirt       $30.00
1  WRANGLER  Wrangler&#174; x Fender&#174; Shrunken T-Shirt       $30.00
2  WRANGLER    Wrangler&#174; x Fender&#174; Record T-Shirt       $30.00
3  WRANGLER   Wrangler&#174; x Fender&#174; Vintage T-Shirt       $30.00
4       NaN                                             NaN          NaN

  Sale Price    Cost  Discount Desc  OH + OO  On Hand Current  \
0     $30.00  $12.00            NaN     28.0             28.0
1     $30.00  $12.00            NaN      3.0              3.0
2     $30.00  $12.00            NaN      2.0              2.0
3     $30.00  $12.00            NaN      NaN              NaN
4        NaN     NaN            NaN     33.0             33.0

   Average of Margin $ (LCM)  On Order (PO) All Stores and Dates  SKU6 Count  \
0                         18                                 NaN         1.0
1                         18                                 NaN         1.0
2                         18                                 NaN         1.0
3                         18                                 NaN         NaN
4                         18                                 NaN         3.0

   SKU10 Count
0          3.0
1          2.0
2          2.0
3          NaN
4          7.0

In [61]:
WR15_drop_receive_date = WR15.dropna(subset=['Receive Date Last'])
WR15_drop_receive_date

,Margin,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count
0,$18.00,542325.0,2022-04-08,62-130 - S/s Branded Tee shirts,WRANGLER,Wrangler&#174; x Fender&#174; Ringer T-Shirt,$30.00,$30.00,$12.00,NaN,28.0,28.0,18,NaN,1.0,3.0
1,$18.00,542326.0,2022-04-08,62-130 - S/s Branded Tee shirts,WRANGLER,Wrangler&#174; x Fender&#174; Shrunken T-Shirt,$30.00,$30.00,$12.00,NaN,3.0,3.0,18,NaN,1.0,2.0
2,$18.00,545424.0,2022-05-04,62-130 - S/s Branded Tee shirts,WRANGLER,Wrangler&#174; x Fender&#174; Record T-Shirt,$30.00,$30.00,$12.00,NaN,2.0,2.0,18,NaN,1.0,2.0
3,$18.00,542323.0,2022-05-04,62-130 - S/s Branded Tee shirts,WRANGLER,Wrangler&#174; x Fender&#174; Vintage T-Shirt,$30.00,$30.00,$12.00,NaN,NaN,NaN,18,NaN,NaN,NaN

## WR16 include skus
### 544394, 544202, 546546, 543457, 544735, 544218

In [ ]:
# Assign rule to dataframe
WR16 = dict_df.get("WR16.Gals(REG)SKU")
print(WR15)

In [ ]:
WR16_drop_receive_date = WR16.dropna(subset=['Receive Date Last'])
WR16_drop_receive_date

In [62]:
all_df = pd.concat([MR1_drop_receive_date, MR2_drop_receive_date, MR3_drop_receive_date, MR4_drop_receive_date, MR5_drop_receive_date, WR1A_drop_receive_date, WR1B_drop_receive_date, WR1C_drop_receive_date, WR2_drop_receive_date, WR3_drop_receive_date, WR4_drop_receive_date, WR5_drop_receive_date, WR6_drop_receive_date, WR7_drop_receive_date, WR8_drop_receive_date, WR9_drop_receive_date, WR10_drop_receive_date, WR11A_drop_receive_date, WR11B_drop_receive_date, WR12_drop_receive_date, WR13_drop_receive_date, WR14_drop_receive_date, WR15_drop_receive_date, WR16_drop_receive_date], axis=0)

In [63]:
all_df

,MARGIN,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count,Margin
1,$20.00,960964.0,2023-02-08,41-800 - Hats/caps,Oakley,Oakley Original Trucker Hat,$30.00,$30.00,$10.00,NaN,2261.0,1061.0,20.00,1200.0,1.0,1.0,NaN
2,$20.00,451985.0,2023-03-08,12-140 - Ss Tees,JUNKFOOD,Junkfood Ford Bronco T-Shirt,$29.50,$29.50,$9.50,NaN,1061.0,1061.0,20.00,NaN,1.0,5.0,NaN
3,$20.00,451986.0,2023-03-08,12-140 - Ss Tees,JUNKFOOD,Junkfood Busch Light&#174; Mountain T-Shirt,$29.50,$29.50,$9.50,NaN,1034.0,1034.0,20.00,NaN,1.0,5.0,NaN
4,$20.00,451558.0,2023-02-13,12-140 - Ss Tees,JUNKFOOD,Junkfood Coors&#174; Banquet Golden T-Shirt,$29.50,$29.50,$9.50,NaN,996.0,996.0,20.00,NaN,1.0,5.0,NaN
5,$20.00,451983.0,2023-02-15,12-140 - Ss Tees,JUNKFOOD,Junkfood Budweiser&#174; Label T-Shirt,$29.50,$29.50,$9.50,NaN,907.0,907.0,20.00,NaN,1.0,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,NaN,965478.0,2022-11-07,96-900 - Boots,Sorel,Girls - Sorel Explorer&#8482; Leather Boot,$105.00,$105.00,$47.25,NaN,64.0,64.0,57.75,NaN,1.0,5.0,$57.75
0,NaN,542325.0,2022-04-08,62-130 - S/s Branded Tee shirts,WRANGLER,Wrangler&#174; x Fender&#174; Ringer T-Shirt,$30.00,$30.00,$12.00,NaN,28.0,28.0,18.00,NaN,1.0,3.0,$18.00
1,NaN,542326.0,2022-04-08,62-130 - S/s Branded Tee shirts,WRANGLER,Wrangler&#174; x Fender&#174; Shrunken T-Shirt,$30.00,$30.00,$12.00,NaN,3.0,3.0,18.00,NaN,1.0,2.0,$18.00
2,NaN,545424.0,2022-05-04,62-130 - S/s Branded Tee shirts,WRANGLER,Wrangler&#174; x Fender&#174; Record T-Shirt,$30.00,$30.00,$12.00,NaN,2.0,2.0,18.00,NaN,1.0,2.0,$18.00
3,NaN,542323.0,2022-05-04,62-130 - S/s Branded Tee shirts,WRANGLER,Wrangler&#174; x Fender&#174; Vintage T-Shirt,$30.00,$30.00,$12.00,NaN,NaN,NaN,18.00,NaN,NaN,NaN,$18.00

In [64]:
# export to excel spreadsheet rename
all_df.to_excel("SFS__REG_SKU_Upload3.24.23.xlsx")

In [65]:
# import latest markdown sheet to combine with reg skus

md_df = pd.read_excel('Sales Summary on server(SFSgroupAll.REC)3.14.xlsm',
                       sheet_name=['SKUUploadMD3.7'])

In [66]:
md_df

{'SKUUploadMD3.7':        MARGIN     SKU Receive Date Last                         Class Desc  \
 0      $32.25  447322        2022-11-17  12-615 - Ls Mid Weight fashion hd
 1      $22.61  966952        2022-11-12            43-410 - Comfort Casual
 2      $19.14  967575        2022-11-11             41-350 - Miscellaneous
 3      $13.98  447771        2022-11-05      12-135 - Ss Tee Pieced bodies
 4      $22.61  967285        2022-11-03            43-410 - Comfort Casual
 ...       ...     ...               ...                                ...
 28546   $8.57  962029        2021-06-25             93-020 - Shoes Seconds
 28547   $8.57  962102        2021-08-24             93-020 - Shoes Seconds
 28548   $8.57  962030        2021-06-25             93-020 - Shoes Seconds
 28549   $8.57  962105        2021-08-19             93-020 - Shoes Seconds
 28550   $8.57  962028        2021-06-25             93-020 - Shoes Seconds

               BRDNM                     Product Name Retail Price Sale Price  \
 0      BUCKLE BLACK  Buckle Black Waffle Knit Hoodie       $49.95     $39.96
 1          Hey Dude   HEYDUDE&#8482; Wally Flow Shoe       $59.95     $44.95
 2               BKE      BKE 3 Pack Holiday Gift Set       $36.95     $26.95
 3          Fox Head        Fox Racing Ryaktr T-Shirt       $34.95     $27.96
 4          Hey Dude        HEYDUDE&#8482; Wally Shoe       $59.95     $44.95
 ...             ...                              ...          ...        ...
 28546        VERY G          Very G Zuma Casual Shoe       $49.95     $22.97
 28547        VERY G                Very G Regan Shoe       $49.95     $22.97
 28548        VERY G          Very G Zuma Casual Shoe       $49.95     $22.97
 28549        VERY G                 Very G Shea Shoe       $49.95     $22.97
 28550        VERY G         Very G Emily Casual Shoe       $42.95     $22.97

          Cost Discount Desc  OH + OO  On Hand Current  \
 0       $7.71       20% off     44.0             44.0
 1      $22.34      $015 off    701.0            701.0
 2       $7.81      $010 off   2234.0           2234.0
 3      $13.98       20% off    721.0            721.0
 4      $22.34      $015 off    255.0            255.0
 ...       ...           ...      ...              ...
 28546  $14.40        022.97      9.0              9.0
 28547  $14.40        022.97      6.0              6.0
 28548  $14.40        022.97      5.0              5.0
 28549  $14.40        022.97      1.0              1.0
 28550  $14.40        022.97      NaN              NaN

        Average of Margin $ (LCM)  date  year
 0                          32.25   NaN   NaN
 1                          22.61   NaN   NaN
 2                          19.14   NaN   NaN
 3                          13.98   NaN   NaN
 4                          22.61   NaN   NaN
 ...                          ...   ...   ...
 28546                       8.57   NaN   NaN
 28547                       8.57   NaN   NaN
 28548                       8.57   NaN   NaN
 28549                       8.57   NaN   NaN
 28550                       8.57   NaN   NaN

 [28551 rows x 15 columns]}

In [67]:
md = md_df.get("SKUUploadMD3.7")
print(md)

       MARGIN     SKU Receive Date Last                         Class Desc  \
0      $32.25  447322        2022-11-17  12-615 - Ls Mid Weight fashion hd
1      $22.61  966952        2022-11-12            43-410 - Comfort Casual
2      $19.14  967575        2022-11-11             41-350 - Miscellaneous
3      $13.98  447771        2022-11-05      12-135 - Ss Tee Pieced bodies
4      $22.61  967285        2022-11-03            43-410 - Comfort Casual
...       ...     ...               ...                                ...
28546   $8.57  962029        2021-06-25             93-020 - Shoes Seconds
28547   $8.57  962102        2021-08-24             93-020 - Shoes Seconds
28548   $8.57  962030        2021-06-25             93-020 - Shoes Seconds
28549   $8.57  962105        2021-08-19             93-020 - Shoes Seconds
28550   $8.57  962028        2021-06-25             93-020 - Shoes Seconds

              BRDNM                     Product Name Retail Price Sale Price  \
0      BUCKLE BLACK  Buckle Black Waffle Knit Hoodie       $49.95     $39.96
1          Hey Dude   HEYDUDE&#8482; Wally Flow Shoe       $59.95     $44.95
2               BKE      BKE 3 Pack Holiday Gift Set       $36.95     $26.95
3          Fox Head        Fox Racing Ryaktr T-Shirt       $34.95     $27.96
4          Hey Dude        HEYDUDE&#8482; Wally Shoe       $59.95     $44.95
...             ...                              ...          ...        ...
28546        VERY G          Very G Zuma Casual Shoe       $49.95     $22.97
28547        VERY G                Very G Regan Shoe       $49.95     $22.97
28548        VERY G          Very G Zuma Casual Shoe       $49.95     $22.97
28549        VERY G                 Very G Shea Shoe       $49.95     $22.97
28550        VERY G         Very G Emily Casual Shoe       $42.95     $22.97

         Cost Discount Desc  OH + OO  On Hand Current  \
0       $7.71       20% off     44.0             44.0
1      $22.34      $015 off    701.0            701.0
2       $7.81      $010 off   2234.0           2234.0
3      $13.98       20% off    721.0            721.0
4      $22.34      $015 off    255.0            255.0
...       ...           ...      ...              ...
28546  $14.40        022.97      9.0              9.0
28547  $14.40        022.97      6.0              6.0
28548  $14.40        022.97      5.0              5.0
28549  $14.40        022.97      1.0              1.0
28550  $14.40        022.97      NaN              NaN

       Average of Margin $ (LCM)  date  year
0                          32.25   NaN   NaN
1                          22.61   NaN   NaN
2                          19.14   NaN   NaN
3                          13.98   NaN   NaN
4                          22.61   NaN   NaN
...                          ...   ...   ...
28546                       8.57   NaN   NaN
28547                       8.57   NaN   NaN
28548                       8.57   NaN   NaN
28549                       8.57   NaN   NaN
28550                       8.57   NaN   NaN

[28551 rows x 15 columns]

In [68]:
reg_md = pd.concat([all_df, md], axis=0)

In [69]:
reg_md

,MARGIN,SKU,Receive Date Last,Class Desc,BRDNM,Product Name,Retail Price,Sale Price,Cost,Discount Desc,OH + OO,On Hand Current,Average of Margin $ (LCM),On Order (PO) All Stores and Dates,SKU6 Count,SKU10 Count,Margin,date,year
1,$20.00,960964.0,2023-02-08,41-800 - Hats/caps,Oakley,Oakley Original Trucker Hat,$30.00,$30.00,$10.00,NaN,2261.0,1061.0,20.00,1200.0,1.0,1.0,NaN,NaN,NaN
2,$20.00,451985.0,2023-03-08,12-140 - Ss Tees,JUNKFOOD,Junkfood Ford Bronco T-Shirt,$29.50,$29.50,$9.50,NaN,1061.0,1061.0,20.00,NaN,1.0,5.0,NaN,NaN,NaN
3,$20.00,451986.0,2023-03-08,12-140 - Ss Tees,JUNKFOOD,Junkfood Busch Light&#174; Mountain T-Shirt,$29.50,$29.50,$9.50,NaN,1034.0,1034.0,20.00,NaN,1.0,5.0,NaN,NaN,NaN
4,$20.00,451558.0,2023-02-13,12-140 - Ss Tees,JUNKFOOD,Junkfood Coors&#174; Banquet Golden T-Shirt,$29.50,$29.50,$9.50,NaN,996.0,996.0,20.00,NaN,1.0,5.0,NaN,NaN,NaN
5,$20.00,451983.0,2023-02-15,12-140 - Ss Tees,JUNKFOOD,Junkfood Budweiser&#174; Label T-Shirt,$29.50,$29.50,$9.50,NaN,907.0,907.0,20.00,NaN,1.0,5.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28546,$8.57,962029.0,2021-06-25,93-020 - Shoes Seconds,VERY G,Very G Zuma Casual Shoe,$49.95,$22.97,$14.40,022.97,9.0,9.0,8.57,NaN,NaN,NaN,NaN,NaN,NaN
28547,$8.57,962102.0,2021-08-24,93-020 - Shoes Seconds,VERY G,Very G Regan Shoe,$49.95,$22.97,$14.40,022.97,6.0,6.0,8.57,NaN,NaN,NaN,NaN,NaN,NaN
28548,$8.57,962030.0,2021-06-25,93-020 - Shoes Seconds,VERY G,Very G Zuma Casual Shoe,$49.95,$22.97,$14.40,022.97,5.0,5.0,8.57,NaN,NaN,NaN,NaN,NaN,NaN
28549,$8.57,962105.0,2021-08-19,93-020 - Shoes Seconds,VERY G,Very G Shea Shoe,$49.95,$22.97,$14.40,022.97,1.0,1.0,8.57,NaN,NaN,NaN,NaN,NaN,NaN
28550,$8.57,962028.0,2021-06-25,93-020 - Shoes Seconds,VERY G,Very G Emily Casual Shoe,$42.95,$22.97,$14.40,022.97,NaN,NaN,8.57,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
# export to excel spreadsheet rename
reg_md.to_excel("SFS__REG&MD_SKU_Upload3.24.23.xlsx")